// Public surface of @kodax-space/space-ipc-schema.
//
// 消费端：
//   - main:     import { invokeChannels, ok, fail } from '@kodax-space/space-ipc-schema'
//   - preload:  import { INVOKE_CHANNEL_NAMES, PUSH_CHANNEL_NAMES } from '...'
//   - renderer: import type { ChannelInput, ChannelOutput, IpcResult } from '...'
//
// FEATURE_001 时这里只有一个最小 versionChannel；FEATURE_002 起完整 envelope + registry。

export {
  IPC_ERROR_CODES,
  ipcErrorSchema,
  ok,
  fail,
  type IpcError,
  type IpcErrorCode,
  type IpcResult,
} from './envelope.js';

export { truncateZodError, type SafeZodIssue, type SafeZodErrorDetails } from './utils.js';

export { canonProjectRoot } from './path-canon.js';

export { invokeChannels, pushChannels } from './channels/index.js';
export type { InvokeChannels, PushChannels } from './channels/index.js';

export {
  versionChannel,
  spaceCapabilitySchema,
  spaceCapabilityStatusSchema,
  type SpaceCapability,
  type SpaceCapabilityStatus,
  type SpaceVersionOutput,
} from './channels/version.js';

export {
  MAX_SANDBOX_DIAGNOSTICS,
  MAX_SANDBOX_GUIDANCE,
  MAX_SANDBOX_STATUS_TEXT,
  sandboxBackendSchema,
  sandboxLastOperationSchema,
  sandboxReadinessSchema,
  sandboxRefreshChannel,
  sandboxSetupChannel,
  sandboxStatusChannel,
  sandboxStatusSchema,
  type SandboxBackendT,
  type SandboxLastOperationT,
  type SandboxReadinessT,
  type SandboxStatusT,
} from './channels/sandbox.js';

export {
  runtimeProfileSnapshotChannel,
  runtimeProfileChangedChannel,
  runtimeConnectionChangedChannel,
  sessionLiveSnapshotChannel,
  sessionLiveChangedChannel,
  sessionLiveInvalidatedChannel,
  spaceRuntimeCursorSchema,
  spaceRuntimeInitiatorSchema,
  spaceRuntimeCapabilitySchema,
  spaceCoderConnectionStateSchema,
  spaceCoderConnectionProjectionSchema,
  spaceRuntimeRunPhaseSchema,
  spaceRuntimeRunFailureKindSchema,
  spaceRuntimeRunStopReceiptSchema,
  spaceRuntimeRunStageSchema,
  spaceRuntimeRunProjectionSchema,
  spaceRuntimeSessionProfileSchema,
  spaceRuntimeInteractionSchema,
  spaceRuntimeNotificationSchema,
  spaceRuntimeProfileProjectionSchema,
  spaceRuntimeDraftSchema,
  spaceRuntimeIntegrationHealthSchema,
  spaceRuntimeActiveToolSchema,
  spaceRuntimeToolSandboxSchema,
  spaceRuntimeTodoSchema,
  spaceRuntimeManagedTaskSchema,
  spaceRuntimeSessionSettingsSchema,
  spaceRuntimeQueuedInputSchema,
  spaceRuntimeSidecarMessagePayloadSchema,
  spaceRuntimeSidecarMessageSchema,
  spaceSessionLiveProjectionSchema,
  spaceSessionLiveDomainChangeSchema,
  spaceSessionLiveChangedSchema,
  type SpaceRuntimeCursorT,
  type SpaceRuntimeInitiatorT,
  type SpaceRuntimeCapabilityT,
  type SpaceCoderConnectionStateT,
  type SpaceCoderConnectionProjectionT,
  type SpaceRuntimeRunPhaseT,
  type SpaceRuntimeRunFailureKindT,
  type SpaceRuntimeRunStopReceiptT,
  type SpaceRuntimeRunStageT,
  type SpaceRuntimeRunProjectionT,
  type SpaceRuntimeInteractionT,
  type SpaceRuntimeIntegrationHealthT,
  type SpaceRuntimeProfileProjectionT,
  type SpaceRuntimeToolSandboxT,
  type SpaceRuntimeSidecarMessageT,
  type SpaceRuntimeSessionSettingsT,
  type SpaceSessionLiveProjectionT,
  type SpaceSessionLiveDomainChangeT,
  type SpaceSessionLiveChangedT,
  type SpaceSessionLiveInvalidatedT,
} from './channels/runtime.js';

export {
  diagnosticsLevelSchema,
  diagnosticsComponentSchema,
  diagnosticsExportCategorySchema,
  diagnosticsReportChannel,
  diagnosticsExportChannel,
  type DiagnosticsExportCategory,
} from './channels/diagnostics.js';

export {
  spaceActionIdSchema,
  spaceActionValueSchema,
  spaceActionArgsSchema,
  spaceControlRequestedChannel,
  spaceControlResultSchema,
  spaceControlResolveChannel,
  type SpaceActionIdT,
  type SpaceActionValueT,
  type SpaceActionArgsT,
  type SpaceControlResultT,
} from './channels/space-control.js';

export {
  repointelStatusChannel,
  repointelPrewarmChannel,
  repointelStatusItemSchema,
  type RepointelStatusItemT,
  type RepointelStatusOutput,
} from './channels/repointel.js';

export {
  handoffAcceptChannel,
  handoffChangedChannel,
  handoffDismissChannel,
  handoffFileSchema,
  handoffListChannel,
  handoffStatusSchema,
  type HandoffFileT,
  type HandoffStatusT,
} from './channels/handoff.js';

export {
  sessionCreateChannel,
  sessionPromoteEphemeralChannel,
  sessionSendChannel,
  sessionCancelChannel,
  sessionListChannel,
  sessionDeleteChannel,
  sessionSetTitleChannel,
  sessionSetReasoningModeChannel,
  sessionSetProviderChannel,
  sessionSetPermissionModeChannel,
  sessionSetAutoModeEngineChannel,
  sessionSetAgentModeChannel,
  sessionForkChannel,
  sessionRewindChannel,
  sessionAgentsMdChannel,
  sessionAgentsMdSaveChannel,
  type AgentsFileMeta,
  sessionHistoryChannel,
  sessionLocalNoticeAppendChannel,
  sessionLocalNoticeReplaceChannel,
  sessionListRunningChannel,
  type RunningSessionInfoT,
  type SessionHistoryItem,
  type SessionLocalNotice,
  sessionEventChannel,
  type PermissionMode,
  type AutoModeEngine,
  type AgentMode,
  type ReasoningMode,
  type Surface,
  type SessionMeta,
  type SessionEvent,
  type SessionEventKind,
  type InputArtifact,
  type InputArtifactSource,
  sessionImageAttachmentSchema,
  isSessionAttachmentPreviewUrl,
  type SessionImageAttachment,
  type SessionSendQueueMode,
  type SessionSendRejectionReason,
} from './channels/session.js';

export {
  MAX_SOURCE_IMAGE_BYTES,
  MAX_NORMALIZED_IMAGE_BYTES,
  MAX_SOURCE_IMAGE_BASE64_LENGTH,
  MAX_NORMALIZED_IMAGE_BASE64_LENGTH,
  clipboardSaveImageChannel,
  clipboardReadImageChannel,
  clipboardCleanupSessionChannel,
  clipboardDiscardImageChannel,
} from './channels/clipboard.js';

export {
  shellRevealPathChannel,
  shellOpenDirectoryChannel,
  shellOpenExternalChannel,
} from './channels/shell.js';

export {
  projectListChannel,
  projectOpenDialogChannel,
  projectRecentAddChannel,
  projectRecentRemoveChannel,
  projectRecentRenameChannel,
  projectRecentSetArchivedChannel,
  projectGitStatsChannel,
  projectGitStatusChannel,
  projectGitChangesChannel,
  projectGitFileDiffChannel,
  projectFileSearchChannel,
  projectGitDiffChannel,
  type Project,
  type ProjectGitStatsDaily,
} from './channels/project.js';

export {
  ASK_USER_BACK_SIGNAL,
  ASK_USER_CUSTOM_INPUT_SIGNAL,
  askUserRequestChannel,
  askUserReplyChannel,
  askUserCancelledChannel,
  type AskUserVerdict,
  type AskUserSignal,
  type AskUserToolCall,
  type AskUserQuestionOption,
  type AskUserQuestionAnswer,
  type AskUserReplyValue,
  type AskUserReplyInput,
  type AskUserRequestPayload,
} from './channels/ask-user.js';

export {
  slashDiscoverChannel,
  slashExecChannel,
  type SlashCommandMeta,
  type SlashCommandSource,
} from './channels/slash.js';

export {
  skillDiscoverChannel,
  skillInstallChannel,
  skillInvokeChannel,
  skillMetaSchema,
  type SkillMeta,
  type SkillSource,
} from './channels/skill.js';

export {
  agentDiscoverChannel,
  agentActorTreeSnapshotSchema,
  agentActorSnapshotChannel,
  agentActorChangedChannel,
  externalAgentStatusChannel,
  externalAgentRegistrationListChannel,
  externalAgentReferenceUpsertChannel,
  externalAgentRegistrationRemoveChannel,
  externalAgentDispatchableListChannel,
  externalAgentPreflightChannel,
  externalAgentTaskListChannel,
  externalAgentTaskStartChannel,
  externalAgentTaskEventsChannel,
  externalAgentTaskSendInputChannel,
  externalAgentTaskCancelChannel,
  externalAgentTaskReconcileChannel,
  type AgentMeta,
  type AgentSource,
  type AgentFailure,
  type AgentActorTreeSnapshotT,
  type AgentActorSummaryT,
  type AgentActorLatestTurnT,
  type AgentActorProgressItemT,
  type ExternalAgentRegistrationSummaryT,
  type DispatchableAgentListingT,
  type ExternalAgentTaskT,
  type ExternalAgentTaskEventT,
} from './channels/agent.js';

export {
  mcpDiscoverChannel,
  mcpServersChannel,
  mcpStartChannel,
  mcpStopChannel,
  mcpLogsChannel,
  mcpToolsChannel,
  mcpReloadChannel,
  type McpServerMeta,
  type McpTransport,
  type McpServerStatusT,
  type McpRuntimeStatusT,
} from './channels/mcp.js';

export { kodaxGetDefaultsChannel, type KodaxUserDefaults } from './channels/kodax.js';

export {
  adminPolicySchemaVersion,
  adminAuditCategorySchema,
  adminAuditOutcomeSchema,
  adminPolicySchema,
  adminPolicyUpdateSchema,
  adminAuditEventSchema,
  adminPolicyGetChannel,
  adminPolicySetChannel,
  adminPolicyExportChannel,
  adminAuditListChannel,
  adminAuditExportChannel,
  type AdminAuditCategoryT,
  type AdminAuditOutcomeT,
  type AdminPolicyT,
  type AdminPolicyUpdateT,
  type AdminAuditEventT,
} from './channels/admin.js';

export {
  kodaxQueueGetChannel,
  kodaxQueueChangedChannel,
  type QueuedMessageT,
  type MessagePriorityT,
  type MessageModeT,
  type QueueEventKindT,
} from './channels/queue.js';

export {
  permissionRequestChannel,
  permissionCancelledChannel,
  permissionAnswerChannel,
  permissionListChannel,
  permissionRevokeChannel,
  autoModeDecisionDiagnosticsSchema,
  autoModeOutputWarningCodeSchema,
  type PermissionRisk,
  type PermissionDecision,
  type AutoModeDecisionDiagnostics,
  type AutoModeOutputWarningCode,
  type PermissionToolCall,
  type PermissionRule,
  type PermissionRequestPayload,
  type PermissionCancelledPayload,
} from './channels/permission.js';

export {
  providerListChannel,
  providerSetKeyChannel,
  providerRemoveKeyChannel,
  providerTestChannel,
  providerSetDefaultChannel,
  providerAddCustomChannel,
  providerUpdateCustomChannel,
  providerRemoveCustomChannel,
  providerModelContextWindowChannel,
  customProviderReasoningSchema,
  CUSTOM_PROVIDER_CONTEXT_WINDOW_MIN,
  CUSTOM_PROVIDER_CONTEXT_WINDOW_MAX,
  type ProviderInfo,
  type ProviderProtocol,
  type CustomProviderReasoning,
} from './channels/provider.js';

export {
  filesTreeChannel,
  filesReadChannel,
  filesReadBinaryChannel,
  filesStatChannel,
  filesWebPreviewChannel,
  filesDiffChannel,
  fileNodeSchema,
  MAX_FILE_BYTES,
  MAX_TREE_NODES,
  WEB_PREVIEW_DIAGNOSTIC_MESSAGE_TYPE,
  type FileNodeT,
  type FileStatKindT,
} from './channels/files.js';

export {
  partnerSourceKindSchema,
  partnerSourceTargetKindSchema,
  partnerSourceSchema,
  partnerSourcesListChannel,
  partnerSourcesAddChannel,
  partnerSourcesRemoveChannel,
  type PartnerSourceKindT,
  type PartnerSourceTargetKindT,
  type PartnerSourceT,
} from './channels/partner-source.js';

export {
  partnerCitationResolveChannel,
  partnerCitationResolutionSchema,
  partnerEvidenceLocatorSchema,
  partnerEvidenceUnitSchema,
  partnerIngestionStatusSchema,
  partnerKnowledgeCatalogChannel,
  partnerKnowledgeRefreshChannel,
  partnerKnowledgeScopeSchema,
  partnerKnowledgeScopeSetChannel,
  partnerKnowledgeSelectChannel,
  partnerKnowledgeTraceItemSchema,
  partnerKnowledgeTraceReadChannel,
  partnerKnowledgeTraceSchema,
  partnerMaterialsAdoptChannel,
  partnerMaterialsCatalogChannel,
  partnerMaterialsRemoveChannel,
  partnerMaterialsSelectChannel,
  partnerMaterialSelectionSchema,
  partnerProjectMaterialRelationSchema,
  partnerProjectMaterialTargetSchema,
  partnerEvidenceAccessDecisionSchema,
  partnerEvidenceAccessObservationSchema,
  partnerEvidenceOwnerIdentitySchema,
  partnerEvidenceOwnerVersionRefSchema,
  partnerEvidenceSelectionRefSchema,
  partnerEvidenceVersionSelectorSchema,
  partnerProjectSourceSchema,
  partnerSourceErrorSchema,
  partnerSourceVersionSchema,
  type PartnerCitationResolutionT,
  type PartnerEvidenceLocatorT,
  type PartnerEvidenceUnitT,
  type PartnerIngestionStatusT,
  type PartnerKnowledgeScopeT,
  type PartnerKnowledgeTraceT,
  type PartnerProjectSourceT,
  type PartnerSourceVersionT,
  type PartnerEvidenceAccessDecisionT,
  type PartnerEvidenceAccessObservationT,
  type PartnerEvidenceOwnerIdentityT,
  type PartnerEvidenceOwnerVersionRefT,
  type PartnerEvidenceVersionSelectorT,
  type PartnerMaterialSelectionT,
  type PartnerProjectMaterialRelationT,
  type PartnerProjectMaterialTargetT,
} from './channels/partner-knowledge.js';

export {
  partnerKbSummaryChannel,
  partnerKbPagesChannel,
  partnerKbReadPageChannel,
  partnerKbWritePageChannel,
  partnerKbSearchChannel,
  partnerKbRebuildIndexChannel,
  partnerKbLintChannel,
  partnerKbConfigGetChannel,
  partnerKbConfigSetChannel,
  partnerKbMaintenanceRunChannel,
  partnerKbMaintenanceLastChannel,
  partnerKbPageTypeSchema,
  partnerKbConfidenceSchema,
  partnerKbPageStatusSchema,
  partnerKbPageRefSchema,
  partnerKbPageSchema,
  partnerKbSearchMatchSchema,
  partnerKbLintIssueSchema,
  partnerKbClaimPolicySchema,
  partnerKbConfigSchema,
  partnerKbConfigDiagnosticSchema,
  partnerKbMaintenanceReportSchema,
  type PartnerKbPageTypeT,
  type PartnerKbConfidenceT,
  type PartnerKbPageStatusT,
  type PartnerKbPageRefT,
  type PartnerKbPageT,
  type PartnerKbSearchMatchT,
  type PartnerKbLintIssueT,
  type PartnerKbClaimPolicyT,
  type PartnerKbConfigT,
  type PartnerKbConfigDiagnosticT,
  type PartnerKbMaintenanceReportT,
} from './channels/partner-kb.js';

export {
  partnerFileProposalOperationSchema,
  partnerFileProposalStatusSchema,
  partnerFileProposalRiskSchema,
  partnerFileProposalClassificationSchema,
  partnerFileProposalSafetySchema,
  partnerFileProposalDiffSchema,
  partnerFileProposalSummarySchema,
  partnerFileProposalSchema,
  partnerFileProposalsListChannel,
  partnerFileProposalsGetChannel,
  partnerFileProposalsApplyChannel,
  partnerFileProposalsRejectChannel,
  partnerFileProposalsExportChannel,
  partnerFileProposalsChangedChannel,
  MAX_PARTNER_FILE_PROPOSAL_CONTENT_BYTES,
  MAX_PARTNER_FILE_PROPOSAL_DIFF_BYTES,
  type PartnerFileProposalOperationT,
  type PartnerFileProposalStatusT,
  type PartnerFileProposalSafetyT,
  type PartnerFileProposalDiffT,
  type PartnerFileProposalSummaryT,
  type PartnerFileProposalT,
} from './channels/partner-file-proposal.js';

export {
  MAX_PARTNER_DELIVERY_INLINE_BYTES,
  PARTNER_DELIVERY_URI_PREFIX,
  partnerDeliveryRootKindSchema,
  partnerDeliveryKindSchema,
  partnerDeliveryRefSchema,
  partnerDeliveryReferenceSchema,
  partnerDeliveryResolveStatusSchema,
  formatPartnerDeliveryUri,
  parsePartnerDeliveryUri,
  isPartnerOutputLogicalPath,
  partnerDeliveryPathMatches,
  partnerDeliveriesListChannel,
  partnerDeliveriesGetChannel,
  partnerDeliveriesResolveChannel,
  partnerDeliveriesOutputRootChannel,
  partnerDeliveriesReadBinaryChannel,
  partnerDeliveriesChangedChannel,
  type PartnerDeliveryRootKindT,
  type PartnerDeliveryKindT,
  type PartnerDeliveryRefT,
  type PartnerDeliveryReferenceT,
  type PartnerDeliveryResolveStatusT,
} from './channels/partner-delivery.js';

export {
  MAX_PARTNER_CHECKPOINT_DIFF_BYTES,
  partnerCheckpointOperationSchema,
  partnerCheckpointStatusSchema,
  partnerCheckpointDiffSchema,
  partnerCheckpointSchema,
  partnerCheckpointsListChannel,
  partnerCheckpointsGetChannel,
  partnerCheckpointsRollbackChannel,
  partnerCheckpointsChangedChannel,
  type PartnerCheckpointOperationT,
  type PartnerCheckpointStatusT,
  type PartnerCheckpointDiffT,
  type PartnerCheckpointT,
} from './channels/partner-checkpoint.js';

export { titlebarSetOverlayChannel } from './channels/titlebar.js';

export {
  settingsGetChannel,
  settingsKodaxConfigApplyIntegrationMigrationChannel,
  settingsKodaxConfigGetChannel,
  settingsKodaxConfigPlanIntegrationMigrationChannel,
  settingsKodaxConfigSetCompactionChannel,
  settingsKodaxConfigSetSandboxChannel,
  settingsSetCoderRuntimeModeChannel,
  settingsSetDefaultWorkspaceChannel,
  settingsSetLanguageModeChannel,
  settingsSetTerminalShellChannel,
  settingsSetWindowCloseBehaviorChannel,
  settingsSetRuntimeDefaultsChannel,
  kodaxCompactionSettingsSchema,
  kodaxSandboxEnvironmentNameSchema,
  kodaxSandboxSettingsSchema,
  kodaxIntegrationMigrationPlanSchema,
  kodaxIntegrationMigrationResultSchema,
  kodaxIntegrationConfigSourceSchema,
  KODAX_COMPACTION_TRIGGER_PERCENT_MAX,
  KODAX_COMPACTION_TRIGGER_PERCENT_MIN,
  KODAX_SANDBOX_ENV_NAME_MAX,
  KODAX_SANDBOX_ENV_PASS_MAX,
  languageModeSchema,
  coderRuntimeModeSchema,
  terminalShellPreferenceSchema,
  windowCloseBehaviorSchema,
  supportedLocaleSchema,
  resolveEffectiveLocale,
  type KodaxCompactionSettingsT,
  type KodaxSandboxSettingsT,
  type KodaxConfigOverviewT,
  type KodaxIntegrationConfigSourceT,
  type KodaxIntegrationMigrationPlanT,
  type KodaxIntegrationMigrationResultT,
  type CoderRuntimeModeT,
  type SpaceSettingsT,
  type SpaceRuntimeDefaultsT,
  type LanguageModeT,
  type TerminalShellPreferenceT,
  type WindowCloseBehaviorT,
  type SupportedLocaleT,
} from './channels/settings.js';

export {
  licenseBindingSchema,
  licenseDisplayEditionSchema,
  licenseEditionSchema,
  licenseEnforcementSourceSchema,
  licenseEntitlementEnvelopeSchema,
  licenseEntitlementPayloadSchema,
  licenseExportRequestChannel,
  licenseFeatureIdSchema,
  licenseGetStatusChannel,
  licenseHasFeatureChannel,
  licenseImportEntitlementChannel,
  licenseKindSchema,
  isLicenseActive,
  licenseRequireEntitlementChannel,
  licenseRuntimeStatusSchema,
  licenseStatusSchema,
  type LicenseBindingT,
  type LicenseDisplayEditionT,
  type LicenseEditionT,
  type LicenseEnforcementSourceT,
  type LicenseEntitlementEnvelopeT,
  type LicenseEntitlementPayloadT,
  type LicenseKindT,
  type LicenseRuntimeStatusT,
  type LicenseStatusT,
} from './channels/license.js';

export { notificationShowChannel, notificationClickedChannel } from './channels/notification.js';

export {
  PARTNER_BROWSER_FRAME_NAME_PREFIX,
  PARTNER_BROWSER_MAX_URL_LENGTH,
  partnerBrowserNavigatedChannel,
  windowActivityChannel,
  windowActivityStateSchema,
  windowCompleteExitProgressChannel,
  windowControlActionSchema,
  windowControlChannel,
  windowSetBadgeCountChannel,
  windowStateChannel,
  windowStateSchema,
  type WindowActivityPayload,
  type PartnerBrowserNavigatedPayload,
  type WindowActivityStateT,
  type WindowCompleteExitProgressPayload,
  type WindowControlActionT,
  type WindowSetBadgeCountInput,
  type WindowStateT,
} from './channels/window.js';

export {
  updaterCheckChannel,
  updaterInstallChannel,
  updaterStatusChannel,
  type UpdaterStateT,
} from './channels/updater.js';

export {
  mcpbInstallChannel,
  mcpbUninstallChannel,
  mcpbListChannel,
  mcpbChangedChannel,
  type McpbExtensionT,
} from './channels/mcpb.js';

export {
  terminalCreateChannel,
  terminalWriteChannel,
  terminalResizeChannel,
  terminalKillChannel,
  terminalOutputChannel,
  terminalExitChannel,
  type TerminalCreateInput,
  type TerminalCreateOutput,
  type TerminalOutputPayload,
  type TerminalExitPayload,
} from './channels/terminal.js';

export {
  artifactKindSchema,
  artifactHtmlPermissionsSchema,
  artifactRefSchema,
  artifactCreateChannel,
  artifactListChannel,
  artifactReadChannel,
  artifactReadBinaryChannel,
  artifactDeleteChannel,
  artifactExportChannel,
  artifactOpenWindowChannel,
  artifactPreviewFileChannel,
  artifactChangedChannel,
  ARTIFACT_HTML_FRAME_URL,
  ARTIFACT_HTML_FRAME_MESSAGE_TYPE,
  looksLikeInteractiveHtml,
  MAX_ARTIFACT_CONTENT_BYTES,
  ARTIFACT_MAX_VERSIONS,
  ARTIFACT_PERMISSION_MAX_SOURCES,
  type ArtifactKindT,
  type ArtifactHtmlPermissionsT,
  type ArtifactRefT,
} from './channels/artifact.js';

export {
  workflowListChannel,
  workflowGetChannel,
  workflowEventChannel,
  workflowRerunChannel,
  workflowSaveChannel,
  workflowSavedRenameChannel,
  workflowSavedDeleteChannel,
  workflowProcessItemSchema,
  workflowProcessSnapshotSchema,
  workflowRunSchema,
  type WorkflowProcessStatusT,
  type WorkflowProcessSnapshotT,
  type WorkflowProcessItemT,
  type WorkflowProcessItemStatusT,
  type WorkflowProcessItemKindT,
  type WorkflowProcessSummaryStatusT,
  workflowActivityChannel,
  type WorkflowRunT,
  type WorkflowEventPayload,
  type WorkflowActivityPayload,
  type WorkflowPolicyT,
} from './channels/workflow.js';

export {
  memoryListChannel,
  memoryProposalChannel,
  memoryApproveChannel,
  memoryRejectChannel,
  memoryReadRefChannel,
  memoryCurateChannel,
  memoryPackChannel,
  memoryItemRefSchema,
  memoryActionProposalSchema,
  memoryApplyPreviewSchema,
  memoryApplyResultSchema,
  memoryRejectResultSchema,
  memoryBodySnapshotSchema,
  memoryGovernanceReportSchema,
  memoryPackSchema,
  memoryReviewPlanSchema,
  type MemoryItemRefT,
  type MemoryRefFilterT,
  type MemoryApplyPreviewT,
  type MemoryActionProposalT,
  type MemoryApplyResultT,
  type MemoryRejectResultT,
  type MemoryBodySnapshotT,
  type MemoryGovernanceReportT,
  type MemoryPackT,
  type MemoryReviewPlanT,
} from './channels/memory.js';

export {
  learnedCapabilityActionSchema,
  learnedCapabilityArtifactSchema,
  learnedCapabilityCanaryInvocationSchema,
  learnedCapabilityCarrierSchema,
  learnedCapabilityLifecycleSchema,
  learnedCapabilityProjectionSchema,
  learnedCapabilitySourceSchema,
  learningAcknowledgeChannel,
  learningActionChannel,
  learningChangedChannel,
  learningEventSchema,
  learningGetChannel,
  learningListChannel,
  learningSurfaceSnapshotSchema,
  type LearnedCapabilityActionT,
  type LearnedCapabilityCarrierT,
  type LearnedCapabilityLifecycleT,
  type LearnedCapabilityProjectionT,
  type LearningEventT,
  type LearningSurfaceSnapshotT,
} from './channels/learning.js';

export {
  INVOKE_CHANNEL_NAMES,
  PUSH_CHANNEL_NAMES,
  getInvokeChannel,
  getPushChannel,
  type InvokeChannelName,
  type PushChannelName,
  type ChannelInput,
  type ChannelOutput,
  type PushPayload,
} from './registry.js';

export {
  SPACE_EXTENSION_FRAME_URL,
  SPACE_EXTENSION_FRAME_MESSAGE_TYPE,
  SPACE_EXTENSION_MAX_HTML_BYTES,
  SPACE_EXTENSION_MAX_FRAME_DOCUMENT_CHARACTERS,
  spaceExtensionIdSchema,
  spaceExtensionManifestSchema,
  spaceExtensionSchema,
  spaceExtensionsListChannel,
  spaceExtensionsInstallChannel,
  spaceExtensionsSetEnabledChannel,
  spaceExtensionsUninstallChannel,
  spaceExtensionsViewChannel,
  spaceExtensionsChangedChannel,
  type SpaceExtensionManifestT,
  type SpaceExtensionT,
} from './channels/space-extension.js';
export {
  spaceExpertDefinitionSchema,
  spaceExpertDraftSchema,
  spaceExpertSaveInputSchema,
  spaceExpertRefSchema,
  partnerExpertSnapshotSchema,
  partnerExpertStateSchema,
  spaceExtensionsCatalogChannel,
  spaceExtensionsResolveExpertChannel,
  spaceExtensionsExpertSaveChannel,
  spaceExtensionsExpertDeleteChannel,
  sessionPartnerExpertGetChannel,
  sessionPartnerExpertSetChannel,
  sessionPartnerExpertChangedChannel,
  type SpaceExpertDefinitionT,
  type SpaceExpertDraftT,
  type SpaceExpertSaveInputT,
  type SpaceExpertRefT,
  type PartnerExpertSnapshotT,
  type PartnerExpertStateT,
} from './channels/partner-expert.js';
