// MockKodaXSession — F003 阶段不依赖真实 KodaX，先模拟一个 session 的事件流。
//
// 行为：
//   1. send(prompt) 启动一个 micro-task 序列：thinking_delta → text_delta x N → tool_start → tool_result
//      → iteration_end → session_complete
//   2. 每个 chunk 用 setTimeout 隔开几十毫秒，模拟真实流式
//   3. cancel() 通过 AbortSignal 中断 chunk 序列，emit session_error('cancelled')
//   4. 并发 send：第二次 send 在 in-flight 时直接 reject，不排队（F003 范围内的 send 已经一次跑完才会 ACK）

import type {
  InputArtifact,
  PermissionDecision,
  PermissionMode,
  SessionEvent,
} from '@kodax-space/space-ipc-schema';
import type {
  ManagedSession,
  PermissionRequestFn,
  SendOptions,
  SendResult,
  SessionDisposeOptions,
  SessionCreateOptions,
} from './session-adapter.js';
import { sanitizeForDisplay } from '../permission/sanitize.js';
import { assessRisk } from '../permission/risk.js';
import { recordDiff } from '../ipc/files-core.js';

const CHUNK_DELAY_MS = process.env.KODAX_TEST_ONBOARDING ? 0 : 35;
const ACCEPT_EDITS_AUTO_ALLOWED_TOOLS = new Set([
  'edit',
  'write',
  'multi_edit',
  'insert_after_anchor',
  'read',
  'read_file',
  'glob',
  'grep',
  'ripgrep',
  'search',
  'ls',
  'list_directory',
  'list_files',
  'web_fetch',
  'web_search',
]);

/**
 * 决定 mock 这一轮要"申请"哪个工具的权限。
 *   - prompt 含 "rm" / "delete" / "delete the database" → bash 危险命令（触发 typed-confirm 弹窗）
 *   - prompt 含 "write" → write 工具（medium）
 *   - 其他 → read 工具（low，但首次仍会弹）
 */
function pickMockToolCall(prompt: string): { toolName: string; input: Record<string, unknown> } {
  const lower = prompt.toLowerCase();
  if (
    lower.includes('rm -rf') ||
    lower.includes('delete the database') ||
    lower.includes('drop table')
  ) {
    return {
      toolName: 'bash',
      input: { command: lower.includes('rm') ? 'rm -rf /tmp/test' : 'DROP TABLE users' },
    };
  }
  if (lower.includes('edit') || lower.includes('fix') || lower.includes('refactor')) {
    return {
      toolName: 'edit',
      input: { path: 'README.md', old_string: 'TODO', new_string: 'DONE' },
    };
  }
  if (lower.includes('write') || lower.includes('save') || lower.includes('create')) {
    return {
      toolName: 'write',
      input: {
        path: 'NOTES.md',
        content: '# Notes\n\nGenerated by mock KodaX run.\n',
      },
    };
  }
  if (lower.includes('run') || lower.includes('install') || lower.includes('npm')) {
    return { toolName: 'bash', input: { command: 'npm install' } };
  }
  return { toolName: 'read', input: { path: 'package.json' } };
}

function sleep(ms: number, signal: AbortSignal): Promise<void> {
  if (ms <= 0) {
    if (signal.aborted) {
      return Promise.reject(new DOMException('aborted', 'AbortError'));
    }
    return Promise.resolve();
  }
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => {
      signal.removeEventListener('abort', onAbort);
      resolve();
    }, ms);
    const onAbort = (): void => {
      clearTimeout(t);
      reject(new DOMException('aborted', 'AbortError'));
    };
    signal.addEventListener('abort', onAbort, { once: true });
  });
}

function mockModeDecision(
  mode: PermissionMode,
  toolName: string,
  input: Record<string, unknown>,
): PermissionDecision | null {
  const assessment = assessRisk(toolName, input);
  if (mode === 'plan') return 'deny';
  if (mode === 'auto' && !assessment.dangerous) return 'allow_once';
  if (
    mode === 'accept-edits' &&
    !assessment.dangerous &&
    ACCEPT_EDITS_AUTO_ALLOWED_TOOLS.has(toolName.toLowerCase())
  ) {
    return 'allow_once';
  }
  return null;
}

export class MockKodaXSession implements ManagedSession {
  readonly sessionId: string;
  readonly projectRoot: string;
  /** F008: provider / reasoningMode 可由 IPC 切换 — 直接赋值，下一次 send 读新值。*/
  provider: string;
  reasoningMode: ManagedSession['reasoningMode'];
  /** FEATURE_029: permissionMode 同上策略，session.setPermissionMode IPC 改字段；下次 tool call 生效。*/
  permissionMode: ManagedSession['permissionMode'];
  /** FEATURE_029: auto-mode 子档；mock 不实际跑 guardrail 但需要持有字段供 host setter。*/
  /** AMA/SA — mock 不真切，但需要持有字段供 host setter。*/
  agentMode: ManagedSession['agentMode'];
  /** F045: 工作面归属；mock 不落盘 tag，但需持有字段使 interface 符合 + host meta 透传。*/
  readonly surface: ManagedSession['surface'];
  partnerExpert?: ManagedSession['partnerExpert'];
  partnerConnectors?: ManagedSession['partnerConnectors'];
  ephemeral: boolean;
  /** v0.7.42 P0 wire：mock 不实际用 model，只持有字段供 host setter。*/
  model?: string;
  /** v0.7.42 P0 wire：mock 不实际用 thinking，只持有字段供 host setter。*/
  thinking?: boolean;
  readonly createdAt: number;
  lastActivityAt: number;
  title: string | undefined = undefined;
  /** FEATURE_033 fork 元数据；root session 都为 undefined。*/
  parentSessionId?: string;
  forkPointTurnIdx?: number;

  private readonly emit: (e: SessionEvent) => void;
  private readonly requestPermission: PermissionRequestFn;
  private currentAbort: AbortController | null = null;
  private disposed = false;

  constructor(opts: SessionCreateOptions) {
    this.sessionId = opts.sessionId;
    this.projectRoot = opts.projectRoot;
    this.provider = opts.provider;
    this.model = opts.model;
    this.reasoningMode = opts.reasoningMode;
    this.permissionMode = opts.permissionMode;
    this.agentMode = opts.agentMode ?? 'ama';
    this.surface = opts.surface ?? 'code';
    this.partnerExpert = opts.partnerExpert ? structuredClone(opts.partnerExpert) : undefined;
    this.partnerConnectors = opts.partnerConnectors
      ? structuredClone(opts.partnerConnectors)
      : undefined;
    this.ephemeral = opts.ephemeral ?? false;
    this.createdAt = Date.now();
    this.lastActivityAt = this.createdAt;
    this.parentSessionId = opts.parentSessionId;
    this.forkPointTurnIdx = opts.forkPointTurnIdx;
    this.emit = opts.emit;
    this.requestPermission = opts.requestPermission;
  }

  isRunning(): boolean {
    return this.currentAbort !== null;
  }

  // OC-31 v0.1.9 — `artifacts` 在 mock 路径下被忽略。mock 只回放预录脚本，
  // 没法真把 image 喂给一个 LLM；保留参数让 ManagedSession 接口一致 & 单测可注入。
  async send(
    prompt: string,
    _artifacts?: readonly InputArtifact[],
    _options?: SendOptions,
  ): Promise<SendResult> {
    if (this.disposed) throw new Error(`[mock-session ${this.sessionId}] already disposed`);
    if (this.currentAbort) {
      // Mock does not model queued follow-up prompts; production uses
      // RealKodaXSession with Space's per-session queue.
      throw new Error(`[mock-session ${this.sessionId}] previous send still in-flight`);
    }

    const abort = new AbortController();
    this.currentAbort = abort;
    this.lastActivityAt = Date.now();

    // fire-and-forget；调用方只关心 IPC 层面的 ACK
    void this.runMockStream(prompt, abort.signal).finally(() => {
      if (this.currentAbort === abort) this.currentAbort = null;
    });
    return { accepted: true, queued: false };
  }

  async cancel(): Promise<void> {
    if (this.currentAbort) {
      this.currentAbort.abort();
    }
  }

  async dispose(_options?: SessionDisposeOptions): Promise<void> {
    this.disposed = true;
    if (this.currentAbort) this.currentAbort.abort();
  }

  /** 模拟一次完整 run：thinking → 文本流 → 一次工具调用 → 迭代结束 → 完成。
   *
   * FEATURE_008：mock 顺带 emit work_budget + harness_profile 事件，让 TopBar
   *   有真数据可显示。预算从 0 涨到 ~28（模拟 ~14% 使用率）；profile 默认 H0_DIRECT，
   *   prompt 含 "plan" 时升级到 H2_PLAN_EXECUTE_EVAL（演示徽标切换）
   */
  private async runMockStream(prompt: string, signal: AbortSignal): Promise<void> {
    const sid = this.sessionId;
    try {
      // F008: 起步先推 harness profile + 初始 work budget。
      // review M-code-1：所有 keyword 都加 \b 单词边界——避免 "unreviewed" / "testing"
      // 等子串误触发，让测试 fixture 更稳。
      const profile: 'H0_DIRECT' | 'H1_EXECUTE_EVAL' | 'H2_PLAN_EXECUTE_EVAL' =
        /\b(plan|architect|design)\b/i.test(prompt)
          ? 'H2_PLAN_EXECUTE_EVAL'
          : /\b(check|review|test)\b/i.test(prompt)
            ? 'H1_EXECUTE_EVAL'
            : 'H0_DIRECT';
      this.emit({
        kind: 'harness_profile',
        sessionId: sid,
        profile,
        round: profile === 'H0_DIRECT' ? undefined : 1,
      });
      this.emit({ kind: 'work_budget', sessionId: sid, used: 2, cap: 200 });

      this.emit({ kind: 'thinking_delta', sessionId: sid, text: 'analysing prompt...' });
      await sleep(CHUNK_DELAY_MS, signal);

      // review M1-sec：剥 prompt 中的控制字符 / RTL / 零宽——renderer 把这段直接显示，
      // 也避免未来结构化日志被 ANSI escape 等污染。同 sanitize.ts 同款策略
      const safePromptSnippet = sanitizeForDisplay(prompt, 60);
      const replyChunks = [
        '我收到了你的 prompt: ',
        `"${safePromptSnippet}"`,
        '\n\n',
        '这是 FEATURE_003 阶段的 Mock 回应——',
        '验证 IPC 事件流从 main 到 renderer 完整跑通。',
      ];
      for (const text of replyChunks) {
        this.emit({ kind: 'text_delta', sessionId: sid, text });
        this.lastActivityAt = Date.now();
        await sleep(CHUNK_DELAY_MS, signal);
      }

      const toolId = `mock-tool-${Date.now().toString(36)}`;
      const { toolName, input } = pickMockToolCall(prompt);

      // F007 permission gate：工具调用前先问。被拒绝就 emit tool_result 说明，结束本轮
      const decision =
        mockModeDecision(this.permissionMode, toolName, input) ??
        (await this.requestPermission({ toolId, toolName, input }));
      if (signal.aborted) {
        throw new DOMException('aborted', 'AbortError');
      }
      if (decision === 'deny') {
        this.emit({
          kind: 'tool_start',
          sessionId: sid,
          toolId,
          toolName,
          input,
        });
        await sleep(CHUNK_DELAY_MS, signal);
        this.emit({
          kind: 'tool_result',
          sessionId: sid,
          toolId,
          toolName,
          content: `permission denied: user rejected ${toolName}`,
        });
        await sleep(CHUNK_DELAY_MS, signal);
        this.emit({
          kind: 'iteration_end',
          sessionId: sid,
          iter: 1,
          maxIter: 30,
          tokenCount: 800,
        });
        // review L1-code：deny 路径也推一次最终 budget，避免 UI 停留在初始 2/200
        // 让用户疑惑"我拒绝了却看起来没消耗"
        this.emit({ kind: 'work_budget', sessionId: sid, used: 8, cap: 200 });
        this.emit({ kind: 'session_complete', sessionId: sid });
        return;
      }

      this.emit({
        kind: 'tool_start',
        sessionId: sid,
        toolId,
        toolName,
        input,
      });
      await sleep(CHUNK_DELAY_MS * 2, signal);

      // F009: write/edit 工具完成时把 before/after 写入 diff cache，让 FilePanel 自动跳 diff
      if ((toolName === 'write' || toolName === 'edit') && typeof input.path === 'string') {
        const after =
          toolName === 'write'
            ? typeof input.content === 'string'
              ? input.content
              : ''
            : `[mock-edited content of ${input.path}]\n${
                typeof input.new_string === 'string' ? input.new_string : ''
              }\n`;
        // 注：v0.1.0 阶段 before 用"文件原内容 OR 空"——真实 adapter 会从 KodaX runtime 拿
        const before = toolName === 'write' ? '' : '[mock-original]\nTODO\n';
        recordDiff(this.projectRoot, input.path, before, after);
      }

      this.emit({
        kind: 'tool_result',
        sessionId: sid,
        toolId,
        toolName,
        content:
          toolName === 'read'
            ? '{\n  "name": "kodax-space",\n  "version": "0.1.0-alpha.0"\n}'
            : `[mock] ${toolName} executed with input: ${JSON.stringify(input)}`,
      });
      await sleep(CHUNK_DELAY_MS, signal);

      // F008: 工具完成后预算上涨
      this.emit({ kind: 'work_budget', sessionId: sid, used: 18, cap: 200 });
      await sleep(CHUNK_DELAY_MS, signal);

      this.emit({
        kind: 'iteration_end',
        sessionId: sid,
        iter: 1,
        maxIter: 30,
        tokenCount: 1280,
        tokenSource: 'api',
        usage: {
          inputTokens: 980,
          outputTokens: 300,
          cacheReadInputTokens: 640,
          cacheWriteInputTokens: 96,
        },
      });
      this.emit({
        kind: 'context_budget_snapshot',
        sessionId: sid,
        provider: this.provider,
        model: this.model,
        profile: 'report_only',
        contextWindow: 200_000,
        smallWindow: false,
        pressure: 'low',
        tokenBreakdown: {
          systemPrompt: 240,
          toolSchemas: 180,
          skillCatalog: 80,
          mcpCatalog: 40,
          transcript: 360,
          pendingInput: 120,
          recentToolResults: 60,
          reservedResponse: 200,
          total: 1_280,
        },
        usedTokens: 1_280,
        availableTokens: 198_720,
        usedRatio: 0.0064,
        toolSchemaRatio: 0.0009,
        createdAt: new Date().toISOString(),
      });
      await sleep(CHUNK_DELAY_MS, signal);

      // F008: iteration 结束推一次最终预算
      this.emit({ kind: 'work_budget', sessionId: sid, used: 28, cap: 200 });

      this.emit({ kind: 'session_complete', sessionId: sid });
      this.lastActivityAt = Date.now();
    } catch (err) {
      if (err instanceof DOMException && err.name === 'AbortError') {
        this.emit({ kind: 'session_error', sessionId: sid, error: 'cancelled' });
      } else {
        const message = err instanceof Error ? err.message : String(err);
        this.emit({ kind: 'session_error', sessionId: sid, error: message });
      }
    }
  }
}
