// Space manual topics injected into the SDK kodax_manual tool.
//
// The SDK ships a generic manual for KodaX SDK/CLI. In Space, users ask about the
// desktop UI they can see: providers, sessions, composer, Task Dock, popouts,
// artifacts, workflows, memory, MCP, permissions, and shortcuts. These topics
// layer product guidance over the SDK manual so the in-app assistant keeps the
// original KodaX mechanism facts and answers with the current Space interaction
// model.
//
// Treat this file as the compact AI-facing self manual for KodaX Space. It is not
// a QA checklist by itself; it is the source the agent reads when explaining what
// the product can do and how a user should operate it.

import type { KodaXManualSource, KodaXManualTopicInput } from '@kodax-ai/kodax/coding';

export const SPACE_PRODUCT_NAME = 'KodaX Space';

const text = (...lines: string[]) => lines.join('\n');

type SdkCodingModule = typeof import('@kodax-ai/kodax/coding');
type SdkManualModule = Pick<
  SdkCodingModule,
  'KODAX_UNDERLYING_CAPABILITY_TOPICS' | 'MANUAL_REGISTRY'
>;

function uniqueStrings(values: readonly string[]): string[] {
  return [...new Set(values)];
}

function uniqueSources(values: readonly KodaXManualSource[]): KodaXManualSource[] {
  const seen = new Set<string>();
  return values.filter((source) => {
    const key = `${source.label}\u0000${source.path}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/**
 * An injected topic overrides an SDK topic with the same id. Compose, rather
 * than copy, the installed SDK body so useful KodaX facts survive Space
 * branding and automatically track the exact dependency version.
 */
function inheritSdkManualTopic(
  topic: KodaXManualTopicInput,
  sdkBaseTopicIds: ReadonlySet<string>,
  manualRegistry: SdkManualModule['MANUAL_REGISTRY'],
): KodaXManualTopicInput {
  if (!sdkBaseTopicIds.has(topic.id)) return topic;
  const sdkTopic = manualRegistry[topic.id as keyof typeof manualRegistry];
  if (!sdkTopic) return topic;

  return {
    ...topic,
    body: text(
      '## KodaX Space interaction',
      '',
      topic.body,
      '',
      '## Inherited KodaX SDK mechanism',
      '',
      sdkTopic.body,
    ),
    aliases: uniqueStrings([...(sdkTopic.aliases ?? []), ...(topic.aliases ?? [])]),
    sources: uniqueSources([...(sdkTopic.sources ?? []), ...(topic.sources ?? [])]),
  };
}

const SPACE_MANUAL_TOPIC_OVERLAYS: readonly KodaXManualTopicInput[] = [
  {
    id: 'overview',
    title: 'KodaX Space overview',
    summary:
      'KodaX Space 是 KodaX 的本地优先桌面 AI agent 工作台，面向项目、会话和可审阅工具调用。',
    body: text(
      'KodaX Space 是基于 Electron + React + TypeScript 的桌面客户端，复用 KodaX SDK 内核，不需要单独启动 sidecar。',
      '',
      '主要界面由六部分组成：左侧 Project/Session 导航，顶部 Environment Hub 与全局工具，中央对话流，右侧 Task Dock，底部 composer，以及可覆盖在右侧的 popout 面板。',
      '',
      '核心能力：多 provider/model 切换，本地项目会话，Coder 与 Partner 工作区，权限确认，计划/Diff/任务/终端/预览/MCP/Memory/Workflow popout，图片与文件输入，Artifact/Outputs 产物，repo-intelligence，以及可保存/复跑的 workflow。',
      '',
      'v0.1.45 继续让 Coder 使用 profile-scoped shared daemon：会话、运行、共享设置和交互由 KodaX Runtime 持有并可被多个受信任客户端观察。完整退出使用 KodaX SDK 的 runtimeExitSettlement v2：SDK 在 stop 前持久化精确 owner，Windows 以 durable outcome、进程创建身份和预执行 Job containment 证明完整关闭，并只恢复安全可证的 ACL 残留；同一 boot 内暂时无法证明的 unconfirmed-owner 由 SDK 后台自动重试，应用退出会取消等待。Space 恢复启动会先完成这个结算，再做 owner reconciliation 或启动 daemon，因此不会用新 owner 覆盖旧退出事实；既有 stale inline owner reconciliation 继续由 SDK 原子处理。macOS/Linux 的正常退出继续可用；卡死 Runtime 在同一次系统启动内保持可见阻断且不会按缓存 PID/PGID 发信号，重启系统后由持久 boot identity 自动证明旧进程树消失并恢复精确 owner。Run 的实时边界还要求 managedRunDurability v1；Space 不通过 KodaX 版本号推断生命周期支持。Partner 继续由 Space embedded-inline 持有。',
      '',
      'v0.1.44 把未读结果与待处理权限/AskUser 按唯一 Session 计数投影到 Windows 任务栏/托盘、macOS Dock 和受支持 Linux launcher。已准入的 Windows 完整退出可在托盘后台继续，同一进度可重开查看；普通成功退出保持安静，失败恢复窗口。Task Dock、Repointel 与历史页头使用当前 live/canonical 事实，历史 Session 的 External tasks 能区分正常空态与可重试错误。v0.1.45 再把 ask_user 与 guardrail 授权从全屏模态改为对话流内的聚焦提问卡：全部待答卡并存可答，composer 上方有带计数与定位闪光的召回停靠条，队首卡支持 1-9/Enter/Esc 键盘操作。',
      '',
      'Coder 面向软件研发；Partner 已启用，面向 workspace-first 知识工作，提供 Sources、Knowledge Base、Outputs、checkpoint 写入和本地 policy/audit。KodaX 0.7.67 Reference External Agent 也已接入管理、Workflow 和 Task Dock。',
    ),
    aliases: ['Space', 'KodaX Space', 'KodaX-Space', '桌面端', '客户端', '桌面客户端', '工作台'],
    nextTopics: [
      'self-manual',
      'runtime-host',
      'background-runtime',
      'quickstart',
      'ui-map',
      'composer',
      'context-window-and-session-tokens',
      'providers',
    ],
  },
  {
    id: 'self-manual',
    title: 'What kodax_manual means in Space',
    summary: 'kodax_manual 是 AI 读取的 Space 自说明手册，帮助回答“这个工具怎么用”。',
    body: text(
      '在 Space 会话里，当用户问“怎么配 provider”“右侧面板是什么”“这个按钮怎么用”这类产品使用问题时，AI 会调用 SDK 的 kodax_manual 工具。',
      '',
      'Space 以 KodaX SDK 的底层能力主题为基线，再叠加桌面端语境：按钮在哪、面板做什么、快捷键是什么、哪些功能当前可用或受限。对 provider、配置、权限、工具、Skills、Extensions、MCP、A2A、Session、压缩和 SDK 等继承主题，Space 会保留当前安装 SDK 的原始正文与来源，不复制一份容易过期的摘要。',
      '',
      '因此它可以理解为“工具的自说明/自查手册”：AI 用它核对自己对产品能力和 UI 交互的回答。但它不是完整测试用例，也不能替代人工 QA、发布清单或安全评审。',
    ),
    aliases: ['kodax_manual', 'manual', '自查手册', '自说明手册', '工具手册', '产品手册'],
    nextTopics: ['overview', 'ui-map', 'context-window-and-session-tokens', 'troubleshooting'],
  },
  {
    id: 'runtime-host',
    title: 'Runtime Host, customer mode switching, and release behavior',
    summary:
      'Coder 默认使用共享 daemon；v0.1.45 可在 Settings 中安全切换 Embedded 兼容模式，Partner 始终保持 embedded inline。',
    body: text(
      'Runtime Host 是 Electron main 内部的 owner 适配边界。日常默认选择 Daemon；v0.1.45 在 Settings -> Runtime -> Coder runtime mode 提供客户可见的 Daemon / Embedded 双选开关。Daemon 是推荐模式，Embedded 是 daemon 无法可靠启动、连接或协商能力时的兼容回退。',
      '',
      'v0.1.45 中，Coder daemon 记录稳定 runId、有序事件、transcript 和共享设置，并承接 compact、fork、rewind、队列、权限/AskUser、Workflow 观察与控制、Learning Center、目录/MCP 发现和配置 External Agent 的 Actor/Turn。多个受信任客户端可观察同一 Coder 会话。F141 只增加启动 owner 的安全选择，不改变这些 daemon-native 与 Space host-provider 边界。',
      '',
      'v0.1.44 正式发布使用经过审计并带完整性锁定的 npm Registry KodaX 0.7.93 正式包。完整退出继续要求 SDK runtimeExitSettlement v1；已连接 Runtime 要求 sandboxRuntime v4、crashOutcomeModel v2、daemonOrphanExit v1、daemonShutdownVerification v1、managedRunDurability v1、actorSettlementConvergence v2、sessionEventJournal v1、runtimeEventCoalescing v1、Skill learning-loop v1、integration config resilience v1、Auto LLM guardrail v4、interruptInput v1、actorControlPlane v1、contextCompaction v3、transcriptPaging v1、transcriptSearch v1、runBoundHostTools v2 和精确授权能力协商。sandboxRuntime v4 让 SDK 安全回收不再拥有精确 coordinator lock 的过期同进程排队票据，并用已记录的释放事实收敛 effect owner；它不会越过精确 active lock 或结果未知的进程树。crashOutcomeModel v2 确保 canonical Session 提交先于 managed terminal。Space 不删除锁、不切到 native shell 绕过 effect fence，也不把 Stop unknown 强制改成 idle。',
      '',
      'v0.1.45 正式发布精确锁定 KodaX 0.7.95，并要求 conversationHistory v2、runtimeExitSettlement v2 与 sandboxRuntime v5。Space 只消费 SDK 返回的 canonical conversation 顺序与稳定身份，在 SDK 启动门和已连接 Runtime 两层验证能力；它不按时间戳重排、不按正文猜测去重，也不把历史候选交给 UI 自行解释。同一 Windows boot 的临时 unconfirmed-owner 会自动重试，应用退出会取消恢复等待；恢复未获安全证明时只阻断 sandbox 或竞争 owner，不阻塞无关工作。',
      '当前源码精确锁定 KodaX 0.7.96-beta.1，并要求 sandboxRuntime v11、runtimeAutoModeGuardrail v5、sharedSessionSettings v2、providerCredentialBroker v2 与 effectiveConfig v1。Space 为手动 compact 绑定并回收 operation-scoped keychain lease；Run 的 allowlist 只包含已知 Provider 身份，fallback、classifier、sidecar、Agent 与 Workflow 后代仅在实际 wire call 时按 Provider 精确读取凭据，缺失即失败。配置状态读取 daemon effective value/source，不从 Electron 环境猜测。v11 的 Windows native host 使用 protocol/setup generation 10、逐命令私有 Temp、64 端口 broker 范围与真实 target-start doctor 证明；完整 native bundle 会解包到 app.asar.unpacked，并按 manifest SHA-256 在发布 smoke 中校验。',
      '恢复与支持链路使用 0.7.89 的权威 session.status 和只读 session.diagnostics：终态会话不会因旧的 Run 列表推断而继续被当作活跃 Run；用户导出诊断包时，当前 Coder 会话会附带 phase/stage、Run-owned 子任务数、Stop 结果和结构化生命周期错误，但不会读取或导出 Prompt、对话正文或工具载荷。Agent progress 持久化采用有界合并；若 canonical replacement 结果仍无法确认，Runtime 会在 fail-closed fence 内协调精确同 owner Actor 事实。异主 owner、无 owner 或持续存储故障仍保持 unknown，Space 不会根据已出现回答文本伪造完成。',
      'v0.1.45 保留活动 Session 的输入准入和历史重验边界：发送、interrupt、after-turn、切换 Session、恢复草稿与分页读取会按当前 Session 的稳定拓扑串行化；重新激活已失效但已绘制的页面时，正在进行的 canonical history 读取不会重复或挪动 live turn。每个已接受输入仍绑定精确 runId/turnId，过期 snapshot、data_changed 或其他 Session 的事件不会把回复移动到错误的 query；无法确认身份时保持 fail-closed 或可见的待确认状态，不用正文内容猜测完成。',
      'v0.1.46-alpha.4 把 Run 结束后的 canonical 认证锚定在身份证据上（ADR-009）：terminal-scoped newest 页必须真的包含该 Run turn 的非 user 行（turnId 身份匹配），这一次读取才可以代表 canonical 接管该轮显示；页里还没有该 turn 的行时，连续两次相同 page.revision 证明持久化已收敛且该轮本就无可持久化内容（如 provider 失败轮），才结构性放行；其余情况保持既有有界重试。durable 页为空但 live 已画出 assistant 内容时永不接管（Issue 204 兜底），所以回答完成后立即追问不会让已显示的回答消失，也不需要 Ctrl+R 找回；从不出错的旧路径（无 turnId 证据）行为不变。',
      'v0.1.46-alpha.5 加入前台收敛保证（Issue 206）：canonical 内容的显示不再完全依赖每一条推送通知——窗口可见时每 30 秒以及每次窗口重新聚焦，Space 都会对当前会话做一次 revision/generation 栅栏化的最新页重验（经由完整认证链，不会引入 202/204 类问题）。任何推送丢失（遮盖时的传输丢弃、重连间隙）最多让内容晚约 30 秒出现，正常使用永远不需要手动 Ctrl+R。',
      '',
      'Auto guardrail v4 在 classifier 缺失或失败时保持 fail-safe，并给出有界的 side-query 尝试、阶段、provider/model、耗时和大小元数据；Space 不显示 classifier prompt 或 response。Runtime 的 tool.sandbox 事件只作为活动工具的结构化 containment 事实展示，不复制到 transcript；活动条会区分 Sandboxed、Sandbox fallback 和 No sandbox。fallback 表示工具仍按普通权限策略执行，不等同于命令失败。',
      '',
      'Settings -> Runtime -> 命令沙箱（ASRT）通过宿主控制面展示机器级 doctor readiness、ASRT/backend、有界诊断和 SDK 指引。Refresh 只重跑 doctor；不要让模型通过 Bash 工具嵌套运行 kodax sandbox doctor，Windows 受限账号按设计不能读取宿主持有的 ASRT 状态。Windows 仅在 setup-required 时提供显式确认后的串行 Setup，并在结束后以真实 target-start probe 重新 doctor；macOS/Linux 只提供指引，不自动调用包管理器。启动、普通工具调用、space.version 和诊断导出都不会触发 setup。该 command sandbox 仍不等于完整 F138 文档/native-resource OS 隔离。',
      '',
      'contextCompaction v3 表示压缩前的精确历史先耐久化，再缩减活动上下文；正式版会消费并重绘精确 checkpoint 字节（包括恢复指引），命令式手动压缩也会先把精确 flat Session history 对齐进 lineage，使 compaction entry、first-kept pointer 和压缩后的附件保持在同一活动 lineage 上，同时兼容旧的无后缀 checkpoint。Space 通过有界 page/chunk/search 契约读取可见历史。Root 与持久子 Agent 只能恢复各自隔离的历史，子上下文或 live-only 活动不能替换根会话投影。',
      '',
      'Space 仍负责 renderer 投影、Partner tools/profile/policy、Artifact、Workflow library/start/admin、MCP server 进程与日志、Reference Agent 执行。这些是明确的 host-provider 边界，不应被描述为 daemon-native。',
      '',
      'Coder 缺少必要 daemon capability 时 fail closed，不会把已接受操作静默重放到另一 owner。切换只能在 ManagedSession、running/paused Workflow、非终态 External Agent task、permission/AskUser、待派发 Coder queue、daemon 其他客户端和 active/queued work 全部为空时进行；Space 会完成 owner policy 交接、持久化偏好并自动重启。切换期间，Session、Slash、Workflow、Runtime External Agent、MCP 和 Runtime-affecting Settings 操作都被同一 admission gate 串行化。',
      '',
      'KODAX_SPACE_RUNTIME_HOST=legacy|runtime 只用于旧 v1/v2 或缺失 settings.json 的一次迁移种子；version 3 的持久化 coderRuntimeMode 一旦存在就成为启动真理。新进程会在 Runtime connect 前协调 owner policy：daemon 偏好遇到 unowned inline policy 会恢复 daemon policy，active/unreadable inline owner 则 fail closed。它不再是日常切换接口，也不迁移 Partner。正式构建继续使用 manifest/lock/安装包一致的精确 Registry 依赖，不增加 KodaX 语义版本门禁。',
      'v0.1.45 consumes SDK liveOutputSegments so live rendering, history reconciliation, reconnect hydration, snapshot recovery, and Ctrl+R converge on one transcript; only the effective provider segment is shown. provider.recovery remains a diagnostic event and no longer drives text replacement, content-based deduplication, or host checkpoint replay.',
    ),
    aliases: [
      'Runtime Host',
      'RuntimeHostAdapter',
      'runId',
      'inline runtime',
      'v0.1.33',
      'v0.1.35',
      'Coder runtime mode',
      'Daemon mode',
      'Embedded mode',
      '运行模式切换',
      '运行时宿主',
      '会话回退',
      '事件日志',
    ],
    nextTopics: [
      'overview',
      'background-runtime',
      'sessions',
      'agent-coordination',
      'workflow',
      'mcp',
      'troubleshooting',
    ],
  },
  {
    id: 'background-runtime',
    title: 'Cross-platform Runtime visibility and complete exit',
    summary:
      'Windows 可保留可见托盘；彻底退出优先安全停止 Runtime，遇到任务时可保持开启或只终止当前 Space 的工作后强退。',
    body: text(
      'Windows 点击右上角关闭时，F140 默认询问“最小化到托盘并保留 Runtime”还是“彻底退出”，并可记住选择。Settings -> Preferences -> Close button behavior 可改为每次询问、直接最小化到托盘，或直接进入安全彻底退出；取消不关闭窗口也不修改偏好，重复点击不会打开多个对话框。',
      '',
      '最小化到托盘会销毁主 BrowserWindow 和 React renderer，但保留轻量 Electron main、托盘图标和 Coder Runtime 客户端连接。单击托盘或选择“打开 KodaX Space”会重建主窗口。显式托盘“关闭窗口”只关闭界面，不读取主窗口偏好；托盘不再提供会让 Runtime 失去可见控制面的“退出 Space，保留 Runtime”。',
      '',
      'F145 使用现有未读结果、permissionQueue 与 askUserQueue 计算唯一 Session 数，不建立第二个通知存储。同一 Session 的多个提醒只计一次。Windows 任务栏覆盖图标与托盘显示同一数字，macOS Dock 与受支持的 Linux launcher 使用原生数字角标；读取 Session 或解决交互后清除。不支持角标的 Linux 桌面会安全降级，不影响 Session 工作。',
      '',
      '“彻底退出”、macOS Cmd+Q 和 Linux 的最后窗口退出走同一流程：先同步关闭新的 Coder 操作准入并等待已准入入口结束，再检查 Runtime 管理状态。若 active/queued 任务、待处理权限/AskUser 或其他连接客户端阻止安全退出，对话框提供“保持 Space 开启”和“强行关闭”。关闭对话框等同保持开启。',
      '',
      '选择“强行关闭”会取消当前 Space 所属的 Session Run、Agent Turn、Workflow、外部 Agent、交互和排队输入；共享 Runtime 工作按已认证的 Space 客户端身份和精确任务 ID 过滤，不会因为共用同一个 Session 而取消其他客户端的任务。取消后若 daemon 已空闲且无其他客户端，Space 继续进行同一安全退出结算；若 stop 已接受但最终清理尚未确认，Space 会以恢复模式重新打开可见控制面，而不是静默消失。',
      '',
      '检查通过后，Space 把完整事务交给 KodaX SDK 的 settleKodaXRuntimeExit。SDK 在请求 stop 前写入精确 owner 恢复票据；Windows 同一 boot 内只允许对相同进程创建身份的 daemon 做升级处理，等待 Job supervisor 证明整棵进程树为空，并在全局锁内只恢复匹配的 ACL marker。已发布并由 Space 完整性锁定的 KodaX 0.7.93 会在锁内复查全部 primary/legacy marker，并仅对全部具有规范非当前 boot identity 的集合恢复共享 ACL。混合、缺失、损坏或当前 boot marker 继续阻断，且该恢复路径不进入 Setup/UAC。恢复进程在 owner reconciliation 与 daemon auto-start 之前续做票据：clean/recovered 完成原退出，active work 保持开启，其他不确定状态阻止 replacement owner 并显示指引。prepared stop 不明确时，只用 autoStart:false 连接现存 daemon 的管理面，并以稳定票据和新的 stop attempt 收敛；连接前若旧请求刚进入 draining，会再扫描一次票据。即使 Session/Runtime 初始化已经失败，也不会为退出启动 replacement daemon。macOS/Linux 同一 boot 内不按缓存 PID/PGID 强杀；重启系统后保留票据即可自动恢复。',
      'v0.1.45 正式发布的 KodaX 0.7.95 使用 runtimeExitSettlement v2 与 sandboxRuntime v5：同一 boot 的临时 unconfirmed-owner 会在后台自动重试进程排空、ACL 恢复和 effect-fence 释放，并只在精确 SID 探针证明 sandbox 账号空闲后清除。暂时无法证明时只阻断有竞争风险的 sandbox/owner 操作，不要求用户删除标记，也不阻塞其他无关工作；应用退出会取消仍在等待的自动恢复。',
      '当前源码的 KodaX 0.7.96-beta.1 使用 sandboxRuntime v11：Windows shell 使用 protocol/setup generation 10，宽 profile ACL 只由 setup 收敛；每个命令拥有私有 Temp、runner pipes、精确进程句柄、kill-on-close Job、取消状态与终态证据。网络 broker 使用 64 端口范围支持最多 32 个精确 authority，explicit doctor/setup 证明一次无副作用 target start/exit。Space 不复制这些权威状态，只在启动、daemon 协商和打包 smoke 三处验证公开契约。',
      '',
      'Windows 的 complete-exit 在可见 preflight 准入后隐藏到托盘继续同一 settlement，托盘显示已用时；用户在完成前重开窗口会看到同一条进度。普通 clean/recovered 成功直接退出，不发送系统通知。失败或仍需处理的状态会恢复窗口并显示诊断。previous-boot ACL 阻断会给出重启、支持信息和“打开诊断目录”，Space 不会自动触发 Setup、提升权限或回显 raw marker。',
      '',
      'macOS/Linux 的正常 graceful exit 与 clean 结果可用；若旧 daemon 卡死或缺少 durable success outcome，同一次系统启动内的 Space 不会按缓存 PID/PGID 发信号，因为进程号可能复用。恢复票据会保留精确 owner 和 boot identity；重启操作系统后再正常启动 Space，SDK 会先确认 boot identity 已变化，再自动清理该旧 owner 的 lock/state/policy 并完成 recovered。',
      '',
      'KodaX 的 daemonOrphanExit v1 能力为 Space 新拉起的 daemon 配置 30 秒 orphan grace：Space 崩溃或被强杀导致最后客户端断开后，daemon 在没有其他客户端且 governed work 空闲时自停；若任务仍在运行则等待终态后再自停。普通 CLI 常驻 daemon 未配置该选项，不改变原有常驻语义。',
      '',
      '旧版 0.1.32/0.1.33 若已经留下 daemon，优先运行 `kodax daemon stop --profile coder --timeout-ms 10000 --json` 做协作式停止。若 CLI 无法确认停止，不要根据 daemon.json 的缓存 PID/PGID 直接发送信号，也不要使用 `killall KodaX Space`：进程号可能复用，而且应用、helper 与 daemon 可能共享进程名。请先关闭所有使用该 profile 的客户端并升级到当前源码构建（KodaX 0.7.96-beta.1）或更高兼容版本；若没有持有原始进程句柄的服务管理器或 supervisor 可证明整棵树退出，保留恢复票据并重启操作系统，然后正常启动 Space 让 SDK 自动结算。不要手工删除 effect/exit lock、profile 或 Session 数据。',
    ),
    aliases: [
      'tray',
      'system tray',
      '通知区域',
      '任务栏右下角',
      '后台运行',
      '关闭窗口',
      '彻底退出',
      '退出 daemon',
      '重新打开 Space',
      'Cmd+Q',
      'orphan daemon',
      'kill daemon',
    ],
    nextTopics: ['runtime-host', 'troubleshooting', 'overview'],
  },
  {
    id: 'install',
    title: 'Install KodaX Space',
    summary:
      'Space 是 Electron 桌面应用，通常从 GitHub Releases 获取安装包，也可源码 npm run dev。',
    body: text(
      'KodaX Space 不作为 npm package 使用。普通用户应从 GitHub Releases 下载对应系统安装包：Windows Setup/Portable，macOS dmg，Linux AppImage/deb。',
      '',
      '首次打开可能遇到 SmartScreen 或 Gatekeeper，因为当前安装包未走公开签名渠道。确认来源可信后按系统提示继续打开。',
      '',
      '源码开发方式：git clone 仓库，npm install --include=dev，然后 npm run dev。开发模式会启动 Vite renderer 与 Electron main watch。',
    ),
    aliases: ['下载', '安装', '安装包', 'installer', 'setup', '怎么装', '怎么下载', '源码启动'],
    nextTopics: ['quickstart', 'providers'],
  },
  {
    id: 'quickstart',
    title: 'Quickstart',
    summary: '首次使用：打开项目，配置 provider，创建/选择会话，在 composer 发出任务。',
    body: text(
      '第一次使用 Space 的最短路径：',
      '',
      '1. 打开 Settings -> Providers，选择内置 provider 或 Add custom，配置 API key/base URL/model，并 Test。',
      '2. 左侧打开一个本地项目目录。项目目录会成为会话 cwd，也是工具读写文件的边界。',
      '3. 新建或选择 session。会话保存上下文、工具调用、计划、Diff、Artifact 和 workflow 记录。',
      '4. 在底部 composer 输入任务，Enter 发送。Shift+Enter 换行，Ctrl/Cmd+Enter 会把消息排到当前 turn 之后，运行中 Esc 或停止按钮可中止。',
      '5. 需要看计划、Diff、终端、预览、MCP、Memory、Workflow 时，用右侧 Task Dock 或顶部 activity popout 打开对应面板。',
    ),
    aliases: [
      '快速开始',
      '入门',
      '上手',
      '怎么用',
      'getting started',
      'how to start',
      '第一次使用',
    ],
    nextTopics: [
      'providers',
      'composer',
      'context-window-and-session-tokens',
      'sessions',
      'task-dock',
      'keyboard-shortcuts',
    ],
  },
  {
    id: 'ui-map',
    title: 'UI map',
    summary:
      'Space 的主界面：左侧项目/会话，顶部环境与活动，中央对话，右侧 Task Dock，底部 composer。',
    body: text(
      '左侧栏：项目列表、最近会话、归档项目、会话切换与项目管理。导航模式和 Files 模式底部都保留 Settings 入口。',
      '后台 Session 等待权限或 ask_user 时，左侧栏显示醒目的等待标记和项目级数量，并在有界列表中优先保留这些 Session。权限 modal 只显示当前可见 Session 的请求；v0.1.45 起 ask_user 与 guardrail 授权以对话流内的聚焦提问卡呈现，全部待答卡并存可答，composer 上方的召回停靠条显示计数并可定位闪光到队首卡。切换 Session 不会丢失耐久队列中的请求。',
      '顶部：Environment Hub 显示当前项目/git/来源/运行摘要；activity 按钮打开 Preview、Diff、Terminal、Agents、MCP、Memory、Workflow 等 popout；Settings 打开配置。',
      '中央：Transcript 显示用户消息、模型回复、工具调用、权限状态、Artifact 卡片和运行事件。',
      '右侧：Task Dock 默认是 Overview；有 Artifact 时可切换 Artifact 标签。Overview 里有 Run、Plan、Agents、Workflow、Changes、Sources、Artifacts、Context 等分区。',
      '底部：composer 输入任务，选择模型、权限模式、agent mode、reasoning effort，附加文件/图片/agent/skill/slash command；右下角把主 Agent 的上下文窗口与整个 Session 的累计 Token 用量分成两个独立入口。',
      '浮层：Command Palette、Quick Ask、Help、Settings、权限请求、workflow 确认、Artifact standalone window。ask_user 与 guardrail 提问卡不是浮层：它们渲染在对话流尾部，对话历史保持可滚动，队首卡支持 1-9 快选、Enter 提交/允许、Esc 取消/阻止。',
    ),
    aliases: ['界面', 'UI', '布局', '主界面', '面板位置', '入口在哪', 'surface'],
    nextTopics: [
      'composer',
      'context-window-and-session-tokens',
      'task-dock',
      'popouts',
      'settings',
    ],
  },
  {
    id: 'composer',
    title: 'Composer input',
    summary: '底部输入框负责消息、附件、文件引用、slash/skill、agent、模式和模型选择。',
    body: text(
      'composer 支持：',
      '- Enter 发送，Shift+Enter 换行，Ctrl/Cmd+Enter 以 after-turn 队列追加。Coder 运行中普通发送会使用 interrupt input，在下一个安全 Runner 边界按 FIFO 交付；它不会创建一条伪装成当前轮的 continuation Run。运行中发送按钮变为停止按钮。',
      '- 已接受的 interrupt 以公开 inputId 跟踪：交付后黄色排队气泡必须由真实用户 transcript 边界替换；若最终安全窗口已经关闭，发送会被拒绝并恢复草稿；极端终态仍未交付时会保留“未送达”失败气泡，不能无限显示为排队中。',
      '- KodaX 0.7.89 的 managedRunDurability v1 要求已接受的首条输入、每个完成回合和每条队列输入在发布相应生命周期事件前先持久化；actorSettlementConvergence v2 只把 canonical replacement 结果未知视为提交歧义。Space 将确认的 runId 绑定到对应 optimistic query，后续 history 重验和 streaming turnId 不会把它归到旧 query。durable run.input.delivered 若失败，Runtime 会保留 queued input、返回错误并只记录不含用户正文的有界 runtime.warning；Space 恢复草稿，不能把 warning 或旧气泡当作已交付。',
      '- 输入 / 打开 slash command 和 skill 补全；输入 @ 打开项目路径补全；上下键在补全和历史消息中导航。',
      '- 粘贴或拖入 PNG/JPEG/WEBP 图片会生成图片 chip；当前 base64/IPC 路径的临时源文件处理上限为 12 MiB，Space 调用 KodaX 将最大边压到 2000 px，并要求最终文件不超过 6 MiB；单轮上限 8 张。',
      '- 拖入或通过 + 菜单添加文件/文件夹：项目内优先插入 @relative/path，项目外插入 file:// 链接；可见消息保留链接，但发送给模型的是经 Electron 校验的原生绝对路径；草稿最多 32 个文件引用。',
      '- + 菜单还可插入 slash command、打开 connectors/MCP、查看 skills。Agent picker 会插入 @agent-name。',
      '- 底部控件可切 provider/model/reasoning、permission mode、agent mode；“上下文窗口”显示主 Agent 到自动压缩阈值的活动输入压力，旁边的“会话 Token 用量”累计根 Agent 与子 Agent 的 Provider 调用，两者不是同一个指标。',
    ),
    aliases: [
      '输入框',
      'composer',
      '底部输入',
      '附件',
      '拖文件',
      '粘贴图片',
      '@文件',
      'plus menu',
      'attach',
    ],
    nextTopics: [
      'slash-commands',
      'image-paste',
      'agent-modes',
      'agent-coordination',
      'providers',
      'permissions',
      'context-window-and-session-tokens',
    ],
  },
  {
    id: 'context-window-and-session-tokens',
    title: 'Context window and Session token usage',
    summary:
      '底部两个指标分别回答“主 Agent 距自动压缩还有多远”和“整个 Session 已累计使用多少 Provider Token”。',
    body: text(
      'Composer 右下角有两个相邻但独立的状态入口：上下文窗口与会话 Token 用量。不要把它们相加，也不要用其中一个解释另一个。',
      '',
      '上下文窗口只表示当前主 Agent 下一次模型请求的活动输入。主数字和进度条都以 Runtime 最终解析出的自动压缩阈值为有效分母，不以模型最大上下文为分母。弹窗把“模型最大上下文”和“自动压缩阈值”作为两个独立事实展示：例如模型最大 1M、当前阈值 320k，并不表示 320k 一定来自 1M 的 50%；绝对值设置或 Runtime 最终策略都可能决定阈值。',
      '',
      '“最近一次模型输入构成”固定列出系统提示词、工具定义、Skills / MCP、对话消息、本次请求输入和近期工具结果六项，当前为 0 的类别也会保留。“本次请求输入”表示最近一次模型调用发出的当前轮输入，不是仍在等待处理的队列；在后续模型调用中，已经完成的用户/助手内容会归入“对话消息”，工具返回会归入“近期工具结果”。各项百分比按自动压缩阈值计算。为下一次回复保留的输出容量不是活动输入，也不是自动压缩前的剩余空间，因此不会作为“输出预留”段强调。Provider 根上下文计数可用时以它为准；只剩 Runtime budget fallback 时，Space 会先减掉 reserved response capacity。',
      '',
      '“距自动压缩还剩”是活动输入到阈值的差值，不是模型最大可输出量。Compact 会降低活动上下文，但不会删除 UI 可回放历史，也不会减少已经发生的会话用量。新的 Session 至少完成一次模型请求后才会出现精确构成。',
      '',
      '会话 Token 用量累计当前 Session 的全部物理 Provider 调用，包含根 Agent 和所有子 Agent。会话总量等于累计输入加累计输出；弹窗先显示输入总量，Provider 有报告时再把输入区分为未缓存输入、缓存命中输入和缓存创建输入。缓存命中与缓存创建都是输入子集，不在总量之外重复相加。不同 Provider 的 tokenizer 与缓存字段口径可能不同，跨模型应比较输入总量和输出，拆分项只反映 Provider 实际返回的字段。弹窗还显示 root/child 调用次数、累计与最近一次缓存命中率；缺失字段显示破折号。/cost 使用同一累计 usage，但最终账单仍以 Provider 为准。',
      '',
      '会话累计量保存在 Space 本地状态中，重开应用不会因 renderer 重建而归零，删除 Session 时会清理。上下文构成事件只含分类 Token 数；Prompt cache 诊断只含哈希、计数、Provider/Model 与 usage，不含系统提示词、消息、工具输入或工具输出正文。',
      '',
      '这两个弹窗的 en-US 与 zh-CN 标签都已配置，跟随 Settings -> Preferences 的界面语言切换。模型输出、Provider 名称和第三方日志不会被强制翻译。',
    ),
    aliases: [
      '上下文窗口',
      '上下文进度',
      '自动压缩阈值',
      '模型最大上下文',
      '会话 Token',
      'Token 用量',
      '缓存命中',
      'context window',
      'auto compact threshold',
      'session token usage',
      'token breakdown',
      'output reserve',
      '输出预留',
    ],
    nextTopics: ['composer', 'sessions', 'settings', 'troubleshooting'],
  },
  {
    id: 'providers',
    title: 'Configure LLM providers',
    summary: 'Settings -> Providers 配置内置或自定义 provider，key 优先存系统 Keychain。',
    body: text(
      '打开 Settings -> Providers，可以搜索、测试、设默认 provider，也可以 Add custom。',
      '',
      '内置 provider 包括常见云端和本地/网关类 provider。每个 provider 可配置 API key、默认 model、base URL 或环境变量来源。Key 优先存系统 Keychain；Keychain 不可用时会退回临时内存状态。',
      '',
      '自定义 provider 支持 OpenAI-compatible 与 Anthropic-compatible 协议，需要 display name、base URL、credential、default model，以及可选 model list/reasoning 声明。只在信任内部网关时跳过 base URL 安全校验。',
      '',
      '会话内可通过模型选择器、/provider、/model、/reasoning 或 /thinking 调整当前运行配置。',
    ),
    aliases: [
      'provider',
      'API key',
      '配置 provider',
      '配 key',
      '配置 API',
      '换模型',
      '模型设置',
      'custom provider',
    ],
    nextTopics: ['custom-providers', 'settings', 'agent-modes', 'config'],
  },
  {
    id: 'custom-providers',
    title: 'Custom providers',
    summary: 'Settings -> Providers -> Add custom 添加 OpenAI/Anthropic 兼容网关或自建模型。',
    body: text(
      'Add custom 用于内部网关、自建模型、OpenAI-compatible 服务或 Anthropic-compatible 服务。',
      '',
      '需要填写：显示名、协议、base URL、credential 方式、默认模型。可补充模型列表和 reasoning effort 声明，让模型选择器知道该 provider 支持哪些思考强度。',
      '',
      '保存后配置写入 KodaX 共享配置；credential 仍按 Space provider 机制存储。Test connection 会用 SDK provider verification 做一次实际握手。',
    ),
    aliases: [
      '自定义 provider',
      '自定义模型',
      'openai compatible',
      'anthropic compatible',
      'baseURL',
      '自建模型',
      '网关',
    ],
    nextTopics: ['providers', 'config'],
  },
  {
    id: 'settings',
    title: 'Settings',
    summary: 'Settings 分 Preferences、Providers、Runtime、License 四类。',
    body: text(
      'Preferences：显示语言、默认 workspace、Smart Popout Director、原生完成通知、workflow policy、Terminal Shell 和主窗口关闭行为。',
      'Providers：内置/custom provider、key 保存与测试、默认 provider、custom provider 管理。',
      'Runtime：KodaX 核心配置概览、compaction 设置、MCP 全局/项目 integrations 配置与 reload、MCP/A2A/Extension health、Skills 用户/项目目录、安装 skill 文件夹/zip/archive。',
      'License：查看社区/授权/过期/降级状态，导入 .kodax-license，导出授权请求，刷新状态。',
      '',
      'Settings 改 UI 偏好和运行时默认值；会话内临时 model/mode 仍可以通过底部控件或 slash command 调整。',
      'Runtime 页面里的 MCP/Skills 是桌面管理入口；同页的 Coder runtime mode 可在无活动工作时把 Coder 从推荐 Daemon 安全切换到 Embedded 兼容模式，或切回 Daemon，并自动重启。Coder 的目录发现与 MCP reload 会同步 daemon，MCP 子进程与日志仍由 Space MCP Manager 管理。Terminal Shell 选择会让 Space PTY 与 Coder 命令工具共享所选 shell 的登录 PATH，同时剥离常见密钥变量。',
    ),
    aliases: ['Settings', '设置', '齿轮', 'preferences', 'runtime', 'license', '配置界面'],
    nextTopics: ['providers', 'config', 'runtime-host', 'mcp', 'skills', 'permissions'],
  },
  {
    id: 'sessions',
    title: 'Projects and sessions',
    summary: '左侧栏管理项目、会话、归档、最近会话和 session 级操作。',
    body: text(
      'Project 是本地工作目录；Session 是围绕某个 project 的连续对话。',
      '',
      '左侧栏可打开/移除/归档项目，项目排序可持久化；展开项目会显示最近会话，更多会话通过 picker overlay 搜索。Session 可以新建、选择、重命名、删除、Fork、Rewind 或通过 /new、/sessions、/load、/delete、/fork、/rewind 等命令管理。',
      '删除 Session 时，列表行会先进入“删除中”状态并禁用重复操作；删除成功后再收起并移除，失败则保留原行和可见错误。',
      '',
      '会话保存模型上下文、工具调用、Artifact、workflow run、计划/Diff/任务等运行状态。跨 KodaX CLI/SDK 共享的历史数据位于 ~/.kodax/sessions。',
      '',
      '长会话 compact 后，0.7.77 保留 compaction v3 的 durable-before-evict 语义：先保存精确 pre-compaction lineage，再发布精简的活动上下文。当前 checkpoint 的恢复指引、first-kept pointer 与压缩后附件会保持在同一活动路径；命令式手动压缩先从精确 flat Session history 对齐 lineage，旧的无后缀 checkpoint 仍可恢复。Space 使用 revision-bound page/chunk/search 读取历史：UI 中的完整可见记录与当前发给模型的活动输入不是同一个指标，子 Agent 压缩也不能覆盖 root 的 token/历史投影。',
      '',
      'KodaX CLI 的 -c/auto-resume 现在会在最近 1000 个候选中跳过空的 ACP 占位会话，只选择最近的非空对话；全部候选为空时不会伪造可恢复会话，显式 Session ID 始终优先。交互式恢复会在下一轮前恢复 workspace runtime、messages、UI history、lineage、artifacts、extensions、title、tag 和 session identity。Space 左侧栏仍使用自己的项目/会话选择和显式恢复入口，不把 CLI 选择器当作第二套 Session owner。',
    ),
    aliases: [
      'session',
      '项目',
      '会话',
      '侧栏',
      'sidebar',
      'project list',
      '项目列表',
      '左侧栏',
      'history',
    ],
    nextTopics: [
      'quickstart',
      'context-window-and-session-tokens',
      'task-dock',
      'agent-coordination',
      'command-system',
    ],
  },
  {
    id: 'task-dock',
    title: 'Task Dock',
    summary:
      '右侧 Task Dock 是当前会话的工作状态总览，可跳转到 Plan、Diff、Workflow、Artifact 等细节。',
    body: text(
      '右侧栏默认显示 Task Dock Overview。若当前会话有 artifacts，顶部可在 Overview 与 Artifact 间切换。',
      '',
      'Overview 分区：Run 显示当前运行/项目/session/权限/ask_user/workflow 摘要；Plan 显示计划；Agents 显示本地子 agent/markdown agent；External tasks 显示第三方 Agent 生命周期、输入、取消、对账和审计事件；Workflow 显示当前 run；Changes 显示 git 状态与变更；Sources 显示 working folder；Artifacts 总览产物；Context 显示本 turn 相关工具与文件引用。',
      '',
      'v0.1.44 以当前 live activity 对齐 Task Dock：活跃 Agent/Workflow 不会被较旧 canonical snapshot 隐藏，结束后也不会被旧状态继续占位。历史持久 Session 没有 External task 时显示正常空态；真正读取失败显示可重试错误，不把主 Run 结果改成失败。',
      '',
      '可展开的分区右上角有打开详情按钮，会进入对应 popout。右侧栏可拖拽左缘调整宽度。',
    ),
    aliases: [
      'Task Dock',
      '任务栏',
      '右侧概览',
      'Overview',
      'Run',
      'Changes',
      'Context',
      'Artifacts summary',
    ],
    nextTopics: ['popouts', 'artifacts', 'workflow', 'environment-hub'],
  },
  {
    id: 'popouts',
    title: 'Popout panels',
    summary:
      '右侧 popout 把 Preview、Diff、Terminal、Agents、MCP、Memory、Workflow、Plan、Tasks、Artifact 独立出来。',
    body: text(
      '顶部 activity 菜单可打开 Preview、Diff、Terminal、Agents、MCP、Memory、Workflow。Task Dock 的分区按钮可打开 Plan、Tasks、Artifact 等详情。',
      '',
      'Preview：输入路径或从变更列表打开文件，PDF/DOCX/XLSX 使用 rich preview，其它文本使用 Monaco 只读。',
      'Diff：显示 AI write/edit 修改与 git working tree 差异。',
      'Terminal：真实 PTY 多标签终端，继承项目 cwd，并剥离常见敏感环境变量。',
      'Agents：显示 AGENTS.md/markdown agents 相关信息。',
      'MCP：查看 server 状态、工具、诊断、.mcpb 扩展安装/卸载。',
      'Memory：Coder memory governance，包括 inbox、refs、governance、hints。',
      'Workflow：查看 runs、saved workflows，pause/resume/stop/rerun/rename/delete/save。',
      '',
      'Smart Popout Director 会在首次出现 plan、diff、task 信号时自动打开相应面板，可在 Preferences 关闭。',
    ),
    aliases: [
      'popout',
      '弹出面板',
      '右栏',
      'right sidebar',
      'preview',
      'diff',
      'terminal',
      'mcp panel',
      'memory panel',
    ],
    nextTopics: [
      'smart-popout-director',
      'preview-terminal',
      'mcp',
      'memory-governance',
      'workflow',
    ],
  },
  {
    id: 'smart-popout-director',
    title: 'Smart Popout Director',
    summary: '首次出现 plan/diff/task 信号时自动打开对应面板，避免用户错过关键状态。',
    body: text(
      'Smart Popout Director 是 Space 的 UI 辅助策略：当当前 session 第一次出现计划、文件改动或任务列表信号时，自动打开 Plan、Diff 或 Tasks 面板。',
      '',
      '每类信号每个 session 只自动触发一次，用户手动关闭后不会反复弹出。Settings -> Preferences 可关闭该行为。',
    ),
    aliases: ['smart popout', '自动弹出', 'auto popout', 'popout director', '自动打开面板'],
    nextTopics: ['popouts', 'task-dock'],
  },
  {
    id: 'preview-terminal',
    title: 'Preview and terminal',
    summary: 'Preview 看文件，Terminal 运行真实 shell；两者都从当前项目上下文出发。',
    body: text(
      'Preview 面板用于检查文件内容。PDF、DOCX、XLS/XLSX 会用专门 viewer；其它文本/代码文件用 Monaco 只读查看；超大或不支持文件会显示错误/截断提示。',
      '',
      'Terminal 面板是真实 PTY，多 tab，可在项目 cwd 中运行命令。Windows 自动模式依次优先 PowerShell 7、Windows PowerShell、cmd，macOS/Linux 走系统 shell；也可在设置中显式选择。新终端与 Coder 命令工具会加载同一个所选 Shell 配置，使 fnm、Volta、nvm、asdf、pyenv 等依赖 PATH 的版本管理器无需专用适配。终端与命令工具仍会剥离常见 *_KEY、*_TOKEN 等敏感变量，降低泄漏风险。',
      '',
      'Preview 适合审阅文件，Terminal 适合用户自己操作环境；AI 需要执行 shell 时仍会走工具权限系统。',
    ),
    aliases: ['预览', 'Preview', '终端', 'Terminal', 'PTY', 'PDF', 'docx', 'xlsx', '文件预览'],
    nextTopics: ['popouts', 'permissions'],
  },
  {
    id: 'artifacts',
    title: 'Artifacts',
    summary: 'Artifact 是 AI 生成的独立产物，可在右侧/弹窗查看、复制、导出、迭代和开独立窗口。',
    body: text(
      'Artifact 用于把“回答中的成果”从聊天流里分离出来，例如 markdown 报告、代码、HTML、interactive HTML、SVG、image、PDF、DOCX、XLSX、chart 等。',
      '',
      'Artifact 视图支持列表选择、版本切换、copy、save/export、再改一版、打开 standalone window。interactive HTML 会进入 sandbox 预览。react artifact 当前是占位类型，不作为可交互 LiveCanvas 运行。',
      '',
      'Artifact 不等于项目文件。它默认是会话产物；需要落到项目里时，用户应明确要求保存到指定路径，之后会走常规写文件权限。',
      '',
      'Agent 侧生成方式（Coder daemon 会话）：KodaX 0.7.89 的 runBoundHostTools v2 会把 lease 绑定的 Space host tools 物化进该 run 的模型可见工具表，create_artifact / create_office_artifact 在 SA 与 managed-agent 子 Agent 两条路径都可直接调用。同一批工具仍保留 MCP 能力通道：用 mcp_search（server 为 "host"）发现，用 mcp_call 调用，capability id 形如 host:<leaseId>:create_artifact。lease 由 Space 自动绑定到它启动的 Coder run，子 Agent 随父 run 继承同一通道。Embedded 回退模式与 Partner 会话仍使用进程内顶层工具。',
    ),
    aliases: [
      'Artifact',
      'Artifacts',
      '产物',
      '文档产物',
      'HTML 产物',
      '导出',
      'standalone window',
      'create_artifact',
      'host tool',
    ],
    nextTopics: ['task-dock', 'workflow', 'permissions'],
  },
  {
    id: 'workflow',
    title: 'Workflows',
    summary: 'Workflow 管理多步骤任务、运行历史和保存后的可复用流程。',
    body: text(
      'Workflow 适合长任务：拆解、多阶段执行、验证、生成产物、保存流程、复跑历史。',
      '',
      '执行入口：带明确 Workflow 意图的请求、/workflow 命令、Workflow Launcher、右侧 Workflow 分区和 Workflow popout。普通复杂任务、并行/审查等弱信号不会自动启动 Workflow。',
      '',
      'Workflow manager 可查看 active/completed runs 与 saved workflows；支持 pause/resume/stop/rerun、rename/delete、把已完成 run 保存成 workflow、运行 saved workflow。启动 saved workflow 前会做 preflight，并在应用内确认。',
      '',
      'v0.1.45 中，Coder Workflow 的列表、详情、事件以及 pause/resume/stop 由 daemon 投影/控制；Workflow library、start/rerun、save、rename/delete 和 prune 仍由 Space Workflow Controller 管理。Partner 全部保留 Space 路径。',
      '',
      'Workflow 面向 Coder session。若当前 Runtime 有可调度的 External Agent，Launcher 可为没有显式 target 的子任务选择默认 Agent，并在启动前按配置修订重新 preflight。危险工具调用仍受 permission mode 和 ask_user 约束。',
    ),
    aliases: ['workflow', '工作流', '/workflow', 'run', 'saved workflow', '复跑', '流程'],
    nextTopics: ['task-dock', 'permissions', 'artifacts'],
  },
  {
    id: 'external-agents',
    title: 'External Agents',
    summary:
      '0.1.30 接入 KodaX 0.7.67 Reference Agent：Space 管理持久任务面，Workflow/Worker 路由并在 Task Dock 干预。',
    body: text(
      'Settings -> Runtime -> External Agents 可创建、编辑、启停、删除和实时预检 Reference Agent 注册。Reference 是本地合规适配器，不访问网络、不直接写 Workspace。',
      '',
      'Workflow Launcher 可从实时 listDispatchable 结果中选择默认子 Agent；Space 在启动前再次 preflight 并固定配置修订。Workflow 源码显式声明的 target 优先。KodaX Worker 也通过同一个 opaque agent_id 目录和 executor plane 调度。',
      '',
      'Task Dock 的 External tasks 独立显示 Task State 与 Cancel State、输出、事件时间线和安全的 artifact/usage 摘要；支持回答 input-required、取消以及对 unknown 状态执行 reconcile。',
      '',
      '历史持久 Session 没有任何 External Agent task 时显示正常空态，不把 session_not_found 伪造成主 Run 失败。真正的读取失败显示不含底层技术细节的可恢复错误与“重试”；已有任务卡仍保留进度、审计、取消和输入操作。',
      '',
      'Runtime 配置的 External Agent 通过 KodaX 0.7.89 的独占 Actor owner 与统一 Actor/Turn 控制面执行；Space 显示其只读注册摘要并提供发现、预检、任务事件、补充输入、中断与 reconcile。`worker.configuredA2A` 是 KodaX CLI 的 Worker-hosted embedded 选项，不是 Space Settings 的开关；Space 仍以 daemon 协商到的 A2A 契约为准。MCP Tasks 与受治理 HTTP 仍不作为通用能力承诺。',
      '',
      'Space Reference Agent 的 durable registration/task/event store 仍由 ExternalAgentGateway 持有；Runtime 配置的 Agent 则由 daemon 持有 Actor/Turn。两条路径以任务 ID 和 adapter kind 显式区分。',
    ),
    aliases: [
      'external agent',
      'third-party agent',
      '第三方 Agent',
      'Reference Agent',
      'Agent Catalog',
      'input-required',
      'reconcile',
    ],
    nextTopics: ['workflow', 'task-dock', 'agent-modes', 'settings'],
  },
  {
    id: 'memory-governance',
    title: 'Memory governance',
    summary: 'Memory 面板管理 Coder 记忆治理；KodaX 0.7.68 还提供静默、受治理的 Memory Agent。',
    body: text(
      'Memory popout 是 Coder-only 的记忆治理界面。需要当前有活跃 Coder session。',
      '',
      'Inbox：查看待批准 memory proposals，按 fingerprint guard 审核 approve/reject，并可给拒绝理由。',
      'Refs：检查已批准记忆引用。',
      'Governance：运行 curator/report，发现过期、冲突或可合并信息。',
      'Hints：为当前任务构建 memory pack/hints，帮助模型在后续 turn 使用稳定上下文。',
      '',
      'KodaX 0.7.68 的 FEATURE_260 Memory Agent 不创建第二套记忆库。它在 managed run 中复用同一 F228 治理面：被动 recall 是零等待、默认静默的低权威提示；模型需要更多历史经验时最多按一个 need 调用只读 memory_recall，scope/identity 不由模型指定。',
      '',
      '任务结束后，SDK 可写入有界 Outcome Digest，并通过 proposal/preview/fingerprint/apply 进入现有治理流程。Space 0.1.45 会在启动时验证 /experimental-memory 契约并记录不含正文的生命周期诊断；完整 Episodes、Activity、correction、forget/purge 桌面体验仍属于后续 F117，不应从版本号推断为已交付。',
      '',
      '当前源码依赖声明是精确 0.7.96-beta.1；Memory Agent 的公开 policy 版本以 SDK 的 /experimental-memory 导出为准。若必需的 export 或 policy shape 缺失，应用启动会 fail-fast，而不是按包版本号或固定 feature 编号伪造能力。现有 Inbox、Refs、Governance 和 Hints 仍由 F228 治理。',
      '',
      'Partner 的 Knowledge Base 是单独的产品面，不等同于 Coder memory governance；Partner 当前已启用。',
    ),
    aliases: [
      'memory',
      '记忆',
      'Memory Governance',
      'Memory Agent',
      'memory_recall',
      'Outcome Digest',
      'experimental-memory',
      '记忆治理',
      'hints',
      'refs',
      'learn',
      '/memory',
      '/learn',
    ],
    nextTopics: ['popouts', 'partner', 'config'],
  },
  {
    id: 'permissions',
    title: 'Permissions and ask_user',
    summary: '权限模式控制写文件/命令等风险操作；ask_user 以对话流内的聚焦提问卡向用户确认信息。',
    body: text(
      '权限档位：Plan 只读规划；Accept Edits 自动批准编辑，shell 与网络边界仍确认；Auto[LLM] 沙箱优先，并在可证明的启动前宿主边界调用 LLM reviewer；Full Access 直接在宿主机执行，但仍受 Exec Policy 约束。',
      '',
      '切换方式：底部 ModeSelector、Shift+Tab 循环、Ctrl+M 打开选择器、/mode plan|accept-edits|auto|full-access。',
      '',
      'Auto 始终表示 Auto[LLM]。旧 auto-in-project、Auto Rules、engine、timeout 与 speculative window 只作为迁移输入，归一后不会继续保存或展示；/auto-engine 与 /auto-denials 已移除。Runtime Shell 先尝试 sandbox；成功时静默完成，只有可证明命令尚未启动的 denial/unavailable 边界才进入 Exec Policy 与固定 LLM reviewer。已启动或结果不确定的命令绝不重放；reviewer 基础设施失败时 fail closed。Full Access 跳过 sandbox 与 Auto review，但不能绕过 Exec Policy。',
      '',
      '当 AI 请求写文件、编辑、运行 bash、MCP 副作用工具等操作时，Space 会弹权限 modal，可 Allow once、Allow always 或 Deny；多个请求可能批量展示。Allow always 只会在 Runtime 为当前安全操作提供精确授权建议时出现，Space 仅回传该建议的 opaque ID；动态或危险 shell 操作不会获得长期允许。',
      'Auto[LLM] 的权限提示会展示经脱敏、限长的 classifier reason，帮助用户理解本次 allow/ask 决策；它不展示 classifier prompt、完整响应或凭据。',
      '',
      '权限和 ask_user 队列按 Session 归属：权限 modal 只显示当前可见 Session 的请求；ask_user 提问卡渲染在该 Session 自己的对话流尾部，每个 reqId 独立结算，互不误答。后台 Session 的请求留在耐久队列，左侧栏会显示等待标记并优先保留这些 Session；切换到对应 Session 后再处理，不能用后台请求阻塞或误答当前会话。',
      '',
      'Auto[rules] 对 PowerShell 路径参数采用 fail-closed 分析：-Path 中的方括号通配符（例如 [.]kodax/config.json）会被视为不完整并升级确认，不能绕过受保护路径；-LiteralPath 或 -PSPath 的方括号表示精确文件名，因此 build/file[12].txt 这类工作区目标仍可按完整模型判断。',
      '',
      'ask_user 是模型主动向用户确认问题的通道。v0.1.45 起问题以对话流尾部的聚焦提问卡呈现（v0.1.44 之前的全屏模态已移除）：select 单选/多选、逐题 multi、文本 input 与带 Other/自定义输入的问题都可在卡内直接作答，多张待答卡并存且互不影响。composer 上方的召回停靠条显示待答计数，点「查看」会滚动定位并闪光队首卡；队首卡支持键盘 1-9 快选、Enter 提交/允许、Esc 取消/阻止，浮层（权限确认、确认对话框、命令面板等）打开时键盘让位。提问卡到达时对话历史仍可自由滚动和搜索。',
    ),
    aliases: [
      '权限',
      'permission',
      'allow',
      '允许',
      '弹窗',
      'plan mode',
      'accept edits',
      'auto mode',
      'ask_user',
      '确认',
    ],
    nextTopics: ['agent-modes', 'workflow', 'tools'],
  },
  {
    id: 'agent-modes',
    title: 'Agent modes and agents',
    summary: '底部可选 AMA、SA；Agent picker 可插入项目/用户 markdown agents。',
    body: text(
      'Agent Mode Selector 控制会话采用的协作形态：AMA 是默认多 agent 编排；SA 是 single-agent 模式。AMAW 已退出。Workflow 只在 KodaX 检测到显式 Workflow 强信号时向 AMA 开放；普通复杂任务、并行、审查或“工作流程”等弱信号不会自动触发。实际行为由 SDK 和当前可用工具共同决定。',
      '',
      'Agent picker 会读取用户目录和项目目录下的 markdown agents，选择后向 composer 插入 @agent-name。AGENTS.md 和 markdown agents 主要用于给模型补充角色、规则和项目约定。',
      '',
      'Agents popout/Task Dock 会显示当前会话相关 agent 状态。',
      '',
      '0.7.77 保留 mailbox 语义的 Agent 协调：模型等待有决策价值的 Agent 消息、完成通知、根用户输入、中断或超时；普通进度继续给 UI/SDK 展示，不会反复唤醒父模型。详情见 agent-coordination。',
    ),
    aliases: [
      'agent mode',
      'agent',
      'agents',
      'AMA',
      'SA',
      'markdown agent',
      '@agent',
      'AGENTS.md',
    ],
    nextTopics: ['composer', 'agent-coordination', 'tools', 'workflow'],
  },
  {
    id: 'agent-coordination',
    title: 'Agent mailbox coordination',
    summary: '0.7.77 保留模型侧 Agent 等待与 UI/SDK 进度遥测分离，避免进度事件重复唤醒父模型。',
    body: text(
      '模型可用 spawn_agent、send_message、followup_task、list_agents、wait_agent、agent_output 和 interrupt_agent 协调 Actor/Turn。Runtime 配置的 Agent、原生子 Agent、Workflow 子任务和 External Agent 都投影到统一树，但每个 Actor 的正文、thinking、工具和 compact 历史保持归属隔离。',
      '',
      'wait_agent 是模型面对的 mailbox yield，不是 Actor 事件读取器。它只接受有界 timeout_ms，并只返回 mailbox、user_input_pending、interrupted 或 wait_expired 这类小型确认。普通 progress、tool activity 和 system reminder 仍可由 Space/SDK 的 events、replay、long-poll 观察，但不会唤醒父模型。actorControlPlane 仍是 v1；这是 v1 内的语义加固，不应伪造 v2 capability。',
      '',
      'Agent 消息和完成证据会在下一安全 Runner 边界一次性进入模型上下文；wait_agent 的结果本身不复制正文。list_agents 用于有界树快照，agent_output 只用于已知 Actor/Turn 的定向结果或 artifact 读取，不能轮询它模拟等待。',
      '',
      '父 Agent 在等待子 Agent 时收到的新用户提示仍是真实用户消息。0.7.77 会把它交给当前 Agent并通知 Space 记录到 transcript，同时绑定正确的 live turn；每条队列消息只出队一次。未确认的 root completion 会在硬重启后恢复一次，同进程 Runtime 重建按 child turnId 去重，已确认或旧版历史完成不会重放。',
      '',
      'Space 的主 transcript 和 root live draft 只显示 root 正文、thinking、工具和 Todo。子 Agent 进度保留在 Agents/Workflow 等专用活动面；若子正文混入父回复，或 wait_agent 因普通进度反复返回，应记录 sessionId、runId、actorPath/turnId 和日志。',
    ),
    aliases: [
      'wait_agent',
      'mailbox',
      '子 Agent',
      '子Agent',
      'subagent',
      'agent progress',
      'agent_output',
      'list_agents',
      '等待子任务',
      'Actor/Turn',
    ],
    nextTopics: ['agent-modes', 'task-dock', 'workflow', 'composer', 'runtime-host'],
  },
  {
    id: 'tools',
    title: 'Agent tools',
    summary:
      'Coder 可用读写、shell、web、artifact、workflow、MCP、memory 等工具；副作用工具受权限约束。',
    body: text(
      'Coder session 使用 SDK 工具集：文件读取/搜索、代码索引、编辑/写入、bash、web_search/web_fetch、artifact 创建、workflow、MCP、memory 等。',
      '',
      '只读工具通常直接运行；写文件、执行命令、会改外部状态的 MCP 工具或敏感操作会进入权限确认。',
      '',
      'create_artifact 生成会话产物，不直接改项目文件。repo-intelligence 是只读仓库理解能力。MCP 工具的可用性取决于 server 状态与工具副作用声明。',
      '',
      'Goal 生命周期工具 get_goal、create_goal、update_goal 在 0.7.77 中保持完整常驻契约，不需要先用 tool_search 解锁；显式创建、完成验证和连续三轮同类 blocker 后才能标记 blocked 的规则仍然有效。其余 deferred 工具保持严格 11 个：6 个 repo-intelligence、4 个 web/code discovery 和 run_workflow。',
      '',
      'Partner 已启用 workspace-first Outputs、Sources/KB、checkpointed writes、Office/PDF 便利产物和 reviewed strict fallback；它不等于 Coder 的完整 coding toolset，也不宣称尚未交付的 Connector、浏览器控制或自动化能力。',
    ),
    aliases: [
      'tools',
      '工具',
      'tool',
      '能用什么工具',
      'agent tools',
      'read tool',
      'bash tool',
      'web_search',
    ],
    nextTopics: ['permissions', 'agent-coordination', 'mcp', 'repo-intelligence', 'artifacts'],
  },
  {
    id: 'mcp',
    title: 'MCP and extensions',
    summary: 'MCP 面板查看 server 状态、工具、诊断和 .mcpb 扩展；Runtime 设置可 reload 配置。',
    body: text(
      'MCP 面板显示 configured MCP servers：idle/connecting/ready/error/disabled 状态、command/url、start/stop、工具列表、诊断信息。',
      '',
      '面板可 Refresh、Reload config、Install extension。已安装 .mcpb 扩展可查看和 uninstall；配置错误会显示并可 reveal 配置路径。',
      '',
      'KodaX 0.7.89 的用户级 MCP 真理文件是 ~/.kodax/integrations/mcp.json，格式为 version 1 + servers。Space 的项目兼容层使用 <project>/.kodax/integrations/mcp.json，并让同名项目 server 覆盖用户 server。Settings -> Runtime 会显示 MCP/A2A/Extension 的规范路径、当前来源、revision、watcher、最近 reload 和有界诊断；/mcp 或 /extensions 可作为命令入口。',
      '',
      '旧 ~/.kodax/config.json#mcpServers 仍可只读兼容，但不是新写入位置。Settings -> Runtime 会直接展示 SDK 迁移计划，并提供“迁移集成配置”按钮；它只创建缺失的分离文件，不覆盖目标，也不删除旧字段。也可使用 `kodax integrations migrate` 预览，再用 `kodax integrations migrate --apply` 生成分离文件；确认目标文件有效后才考虑 `--cleanup-legacy`。`.mcpb` 安装/卸载通过 SDK MCP CRUD 写入新的 integrations/mcp.json。',
      '',
      '0.7.89 对无效更新继续使用 last-known-good，并把 invalid-config、activation-failed 或 watcher-degraded 诊断按域返回。Space 会自动轮询 daemon 管理状态并刷新 Settings 中的集成健康信息；修复被点名文件后通常会在数秒内恢复 healthy，无需重启 Coder。并发写入发现 revision 已改变时，Space 要求 reload 后重试，不覆盖更新的数据。',
      '',
      'Space MCP Manager 拥有 server 子进程、状态和日志；Coder 的 MCP 工具发现/reload 同步 Runtime，但 v0.1.44 不会启动第二套桌面 MCP manager。',
      '',
      'SDK filesystem extensions 与 MCP 是两个概念。/extensions sdk 用于查看 SDK 扩展发现/加载诊断；默认安全策略是发现优先，执行扩展代码需要显式 opt-in。',
      '',
      'Coder daemon 会话还有一个不可配置的内置 host 能力源（server 名 "host"）：它承载 Space host tools（如 create_artifact、create_office_artifact），按 run 绑定的 lease 作用域经 mcp_search/mcp_call 暴露，capability id 形如 host:<leaseId>:<name>。KodaX 0.7.89 的 runBoundHostTools v2 同时会把这些 lease 绑定工具物化进该 run 的模型可见工具表（SA 与 managed-agent 双路径），两条通道指向同一实现。它不是用户配置的 server，不出现在 integrations/mcp.json 中。',
    ),
    aliases: [
      'mcp',
      'model context protocol',
      'mcp server',
      '.mcpb',
      '外部工具',
      'integration',
      'extensions',
      '插件',
    ],
    nextTopics: ['tools', 'settings', 'permissions'],
  },
  {
    id: 'extensions',
    title: 'Extensions',
    summary: '/extensions 汇总 Space MCP 扩展和 SDK 扩展诊断；执行第三方扩展需可信来源。',
    body: text(
      'Space 的扩展面主要有两类：',
      '',
      '1. MCP/.mcpb：通过 MCP 面板安装、查看、启动/停止、卸载，能力会以 MCP tools 暴露给 agent。',
      '2. SDK filesystem extensions：默认目录为 ~/.kodax/extensions，受管理路径声明在 ~/.kodax/integrations/extensions.json（version 1 + paths）。通过 /extensions sdk 查看默认目录、受管理 entrypoint、skipped entries 和运行时诊断。旧 config.json#extensions 仅作为迁移兼容；Settings -> Runtime 的 SDK 迁移计划与按钮会连同 MCP 一起处理，也可用 `kodax integrations migrate` 预览和迁移。',
      '',
      'Space 默认只做发现。只有显式设置 KODAX_SPACE_ENABLE_SDK_EXTENSIONS 后，embedded Space extension runtime 才会把默认目录与 integrations/extensions.json 的路径去重后加载。Extensions 是进程内可信代码；不可信或重量级外部能力应优先使用 MCP。',
      '',
      '只从可信来源安装扩展。会改状态或访问外部资源的扩展工具仍应受权限模式、MCP 工具声明和用户确认约束。',
    ),
    aliases: [
      'extension',
      'extensions',
      'plugin',
      'plugins',
      'sdk extensions',
      '/extensions',
      '扩展',
      '插件',
    ],
    nextTopics: ['mcp', 'permissions', 'settings'],
  },
  {
    id: 'skills',
    title: 'Skills',
    summary:
      'Skill 是 SDK 级能力，Space 在 composer 的 / 补全和 Runtime 设置中暴露安装与调用入口。',
    body: text(
      'Skill 来自用户或项目的 .kodax/skills 目录，以及 Space 安装包内经审查的 builtin 目录，由 SDK SkillRegistry 注入会话。用户/项目同名 Skill 按 KodaX 发现优先级覆盖 builtin，但不会改写安装包文件。',
      '',
      '调用：在 composer 输入 /，skill 会和 slash command 一起出现在补全列表。若名称冲突，可用 /skill:<name> 消歧。',
      'KodaX 0.7.95 保留显式 Skill 源契约：每个 enabled Skill 都可由用户显式调用；disable-model-invocation 只影响模型发现与模型 skill tool，user-invocable 仅保留为兼容元数据，不再充当执行权限。每个请求只能激活一个显式 Skill；多个已注册引用会在展开、Hook 和 Run 准入前拒绝。无效 allowed-tools 或 hook JSON 会由 SDK registry 作为诊断处理，Space 不把无效目录项当作可执行 Skill。持久 transcript 只记录原始 rawUserInput，prepared User request overlay 只用于模型执行。',
      '',
      '安装/管理：Settings -> Runtime -> Skills 显示用户/项目 skill 目录，并可安装文件夹、zip 或 archive。skill-creator 也可生成新的 skill；Space 会在补全打开时刷新 registry，让新 skill 尽快可见。',
      '',
      'Space 0.1.44 继续自带 frontend-slides 和 huashu-design，用户无需另行安装；Space 分发的 huashu-design 适配已移除默认推广水印/签名的标记、指令和悬空代码，同时保留上游 MIT 许可证与作者信息。Builtin 只保证 skill 文件随应用提供，浏览器、视频、TTS、AI 评审等可选流程仍可能需要 Node/Python package、Playwright 浏览器、ffmpeg、POSIX-compatible shell 或 API 凭据。',
      '',
      '本机可能存在的 pdf、pptx、xlsx、docx skill 不随 Space 分发，因为当前来源许可证禁止复制、修改或再分发；这不影响 Space 对相应文件格式的预览能力。',
      '',
      'Skill 是“教 agent 如何做事”的说明，不等同于 MCP 外部工具。',
    ),
    aliases: [
      'skill',
      'skills',
      '技能',
      'builtin skill',
      'frontend-slides',
      'huashu-design',
      'skill creator',
      '生成 skill',
      '加 skill',
      '/skill',
    ],
    nextTopics: ['slash-commands', 'settings', 'tools'],
  },
  {
    id: 'slash-commands',
    title: 'Slash commands',
    summary:
      '输入 / 打开命令/skill 补全；常用命令覆盖 session、mode、provider、workflow、memory、MCP 和诊断。',
    body: text(
      'composer 输入 / 会打开补全；Tab/Enter 可接受补全，Esc 关闭，箭头键导航。',
      '',
      '常用命令：/help、/new、/clear、/copy、/history、/sessions、/load、/delete、/fork、/rewind；/mode、/provider、/model、/reasoning、/thinking、/agent-mode；/workflow；/memory、/learn；/extensions、/mcp；/repointel、/doctor、/status、/review；/compact、/tree、/paste、/reload。',
      '',
      '可用命令会随版本、当前 session、项目和 provider 状态变化，以 /help 与补全列表为准。',
    ),
    aliases: ['slash', '/', '命令', 'slash command', '快捷命令', '/help', '/workflow', '/mode'],
    nextTopics: ['command-system', 'skills', 'keyboard-shortcuts'],
  },
  {
    id: 'command-system',
    title: 'Command palette and help',
    summary: 'Ctrl/Cmd+Shift+P 是全局命令面板；? 打开帮助；/ 是 composer 内命令。',
    body: text(
      'Space 有三类命令入口：',
      '',
      'Command Palette：Ctrl/Cmd+Shift+P 打开，搜索 action、最近 session、文件引用和 slash 命令。适合快速切换视图、会话、主题、面板或执行全局动作。',
      'Slash commands：在 composer 输入 /，把命令作为当前消息/会话的一部分执行。',
      'Help overlay：按 ? 打开帮助，查看常用快捷键和入口。',
      '',
      '这三者不是同一层：Command Palette 操作 UI；slash command 进入 agent/session 命令系统；Help 用来查询。',
    ),
    aliases: [
      '命令面板',
      'command palette',
      'Ctrl+Shift+P',
      'Cmd+Shift+P',
      '帮助',
      'help overlay',
      '?',
    ],
    nextTopics: ['slash-commands', 'keyboard-shortcuts'],
  },
  {
    id: 'image-paste',
    title: 'Image paste',
    summary: 'composer 可粘贴/拖入 PNG、JPEG、WEBP 图片，作为 multimodal 输入发送。',
    body: text(
      '在 composer 中直接粘贴截图或拖入 PNG/JPEG/WEBP 图片，会显示缩略图 chip。发送时 Space 将图片作为 input artifact 传给 SDK，支持 vision 的 provider/model 会收到 multimodal content；若 SDK 将图片规范化为另一种格式，Space 使用持久化字节对应的最终 media type，而不会沿用旧的 PNG/JPEG 标签。',
      '',
      '限制：当前 base64/IPC 路径的临时源文件处理上限为单张 12 MiB；它不是压缩能力阈值。Space 会先调用 KodaX 转换，再要求最终图片不超过 6 MiB。单轮最多 8 张。GIF/视频不保证作为动态图或视频处理。发送前可移除图片 chip。',
    ),
    aliases: [
      '粘图',
      '粘贴图片',
      '截图',
      'paste image',
      'image input',
      '多模态',
      'multimodal',
      'vision',
      '看图',
    ],
    nextTopics: ['composer', 'providers'],
  },
  {
    id: 'quick-ask',
    title: 'Quick Ask',
    summary: 'Ctrl/Cmd+K 打开临时 plan-mode 问答；可 Continue in Coder 提升为正常会话。',
    body: text(
      'Quick Ask 适合临时问一句，不想打断当前主会话时使用。它需要已打开项目，会创建临时 plan-mode code session，流式回答后关闭时会清理临时 session。',
      '',
      '如果答案值得继续推进，点击 Continue in Coder 会把内容提升/接入正常 Coder session 并选中它。',
      '',
      '注意：Quick Ask 不是完全无 session 的 side query；它是受限制的临时 session，默认偏只读。',
    ),
    aliases: ['Quick Ask', 'quick ask', 'Ctrl+K', 'Cmd+K', '临时问答', '快速提问', 'side query'],
    nextTopics: ['sessions', 'permissions', 'keyboard-shortcuts'],
  },
  {
    id: 'environment-hub',
    title: 'Environment Hub',
    summary: '顶部环境按钮显示当前项目、git 状态、运行上下文和来源，并能跳转到 Task Dock 分区。',
    body: text(
      'Environment Hub 是顶部紧凑状态入口。它显示当前项目、git branch/changes/ahead/behind、本地工作位置、sources/session context 等摘要。',
      '',
      '点击后可跳转到 Task Dock 的 Changes、Sources、Run、Context 等分区。git 状态会在窗口 focus、visibility 变化和定时刷新时更新。',
      '',
      '当前主要支持本地 workspace。worktree/cloud 位置入口仍是禁用或后续能力。',
    ),
    aliases: ['Environment Hub', '环境', '顶部状态', 'git 状态', 'workspace', 'sources', 'changes'],
    nextTopics: ['task-dock', 'sessions', 'repo-intelligence'],
  },
  {
    id: 'handoff',
    title: 'Handoff inbox',
    summary: '标题栏 handoff inbox 会接收 ~/.kodax/handoffs 中的会话交接描述。',
    body: text(
      '当 ~/.kodax/handoffs 下存在 handoff 描述时，标题栏会出现 inbox。它会显示有效/总数、stale/error 状态，并允许 accept 或 dismiss。',
      '',
      'Accept 前会验证目标 session 仍存在；成功后移除 descriptor 并切到对应会话。Dismiss 会丢弃该 handoff 描述。',
    ),
    aliases: ['handoff', '交接', 'inbox', 'thread handoff', '会话交接'],
    nextTopics: ['sessions', 'workflow'],
  },
  {
    id: 'partner',
    title: 'Partner surface status',
    summary:
      'Partner surface is available with workspace-first Outputs, checkpointed workspace writes, KB, sources, artifacts, and local policy/audit controls.',
    body: text(
      'Space 有 Coder 与 Partner 两个 surface 概念。Coder 是当前可用的主要工作区。',
      '',
      'Partner includes Sources, Conversation, Artifact/Knowledge Base, Outputs, checkpointed workspace-session writes, generated Office/PDF convenience artifacts, reviewed strict fallbacks, and local policy/audit controls.',
      '',
      'PARTNER_ENABLED is true. The Partner tab is available, and Partner sessions can be restored like other surface-scoped sessions.',
    ),
    aliases: [
      'Partner',
      'partner',
      '伙伴',
      'Knowledge Base',
      'Sources Panel',
      'Partner 不可用',
      '开发中',
    ],
    nextTopics: ['overview', 'memory-governance', 'artifacts'],
  },
  {
    id: 'repo-intelligence',
    title: 'Repository intelligence',
    summary: 'repo-intelligence 为当前项目提供只读仓库理解、符号/模块上下文和预热诊断。',
    body: text(
      '打开项目后，SDK 可按需使用 repo-intelligence：仓库概览、符号查找、模块上下文、文件/引用理解等。',
      '',
      'composer 首次输入时可能 best-effort prewarm 当前项目；/repointel status 或 /repointel warm 可查看/预热诊断。',
      '',
      'v0.1.44 把 Runtime repo-intelligence trace 桥接到 Repointel 状态芯片，使索引/检索活动与当前 Runtime 事实对齐；该芯片只做有界投影，不创建第二份 repo-intelligence 状态。',
      '',
      '这是一组只读能力，不直接修改文件。可用性可能受项目结构、SDK 状态和 license/policy 控制。',
    ),
    aliases: [
      'repo intelligence',
      'repointel',
      '仓库智能',
      '代码索引',
      'symbol',
      '项目结构',
      'codebase',
      '/repointel',
    ],
    nextTopics: ['tools', 'environment-hub', 'sessions'],
  },
  {
    id: 'config',
    title: 'Config and data locations',
    summary:
      '核心配置与 MCP/A2A/Extensions integrations 已分离；Space UI 状态独立保存在 ~/.kodax/space。',
    body: text(
      '~/.kodax/config.json 是 KodaX 核心配置：provider、model、effort、permission、customProviders、compaction、Runtime/Workflow 等。MCP、A2A 和 Extensions 不再把这里当作新配置真理面。',
      '',
      '~/.kodax/integrations/mcp.json 保存用户 MCP servers；~/.kodax/integrations/a2a.json 保存 A2A；~/.kodax/integrations/extensions.json 保存可信 Extension 路径。三者是独立、版本化的严格 JSON 文档，由 KodaX 0.7.89 的公开 reader/CRUD/reload/resilience 契约分别管理；无效新配置保留 last-known-good，revision 冲突要求 reload 后重试。',
      '',
      '旧 config.json#mcpServers 和 config.json#extensions 仍可读取以便迁移。Settings -> Runtime 会调用 SDK 的 planLegacyIntegrationMigration() 显示迁移计划，并通过 migrateLegacyIntegrationConfig() 提供迁移按钮；应用只创建缺失的目标文件，保留旧字段，随后重载 MCP。命令行也可先运行 `kodax integrations migrate` 查看计划，再运行 `kodax integrations migrate --apply`；目标文件已存在时不会被覆盖。只有确认分离文件有效后才运行 `kodax integrations migrate --apply --cleanup-legacy` 显式清理旧字段。A2A 没有旧 config.json 迁移源，integrations/a2a.json 始终是权威配置。',
      '',
      'A2A 的 inbound authentication 或 authority 变更仍可能要求安全重启 Runtime owner；不要把配置文件可 reload 误写为所有 authority 都保证无重启生效。',
      '',
      '~/.kodax/ 还保存 sessions、skills、agents、默认 extensions 目录和 AGENTS.md 等共享数据；项目级 Space MCP 兼容配置放在 <project>/.kodax/integrations/mcp.json。',
      '',
      '~/.kodax/space/ 是 Space 专属层：UI state、main logs、桌面端偏好等。',
      '',
      'Settings -> Runtime 会把核心 config.json 与 MCP/A2A/Extension integration 的路径、来源、revision、watcher、最近 reload 和诊断分别展示，避免把它们误认为同一个文件。',
      '',
      '一般不要手动改 state 文件；若 UI 状态严重损坏，可在备份后重置 ~/.kodax/space/state.json。',
    ),
    aliases: [
      '配置文件',
      '数据目录',
      '存哪',
      'config location',
      'data path',
      '~/.kodax',
      '~/.kodax/space',
      'state.json',
    ],
    nextTopics: ['settings', 'providers', 'troubleshooting'],
  },
  {
    id: 'sidebar-resize',
    title: 'Resize and zoom',
    summary: '左右栏可拖宽；Ctrl+wheel、Ctrl+=、Ctrl+-、Ctrl+0 控制全局缩放。',
    body: text(
      '左侧栏右缘和右侧栏左缘有 resize handle，可拖拽调整宽度；双击通常恢复默认；拖动中 Esc 可取消。',
      '',
      '全局缩放：Ctrl+wheel、Ctrl+=/Ctrl+- 增减，Ctrl+0 重置。右下角会短暂显示当前 zoom factor。',
      '',
      'Transcript 另有视图菜单，可切 Normal/Thinking/Verbose/Summary 和 small/base/large 文本大小；Ctrl+Shift+O 可打开/切换。',
    ),
    aliases: [
      '缩放',
      'zoom',
      '调字号',
      '改大小',
      '拖栏',
      '拖宽',
      '侧栏宽度',
      'sidebar width',
      'resize',
    ],
    nextTopics: ['keyboard-shortcuts', 'ui-map'],
  },
  {
    id: 'keyboard-shortcuts',
    title: 'Keyboard shortcuts',
    summary: '常用快捷键覆盖发送、补全、Quick Ask、命令面板、权限模式、reasoning、面板和缩放。',
    body: text(
      '发送与 composer：Enter 发送，Shift+Enter 换行，Ctrl/Cmd+Enter after-turn 排队，Esc 停止/关闭当前 popover；/ 打开 slash 补全，@ 打开路径补全。',
      '全局：Ctrl/Cmd+K Quick Ask；Ctrl/Cmd+Shift+P 命令面板；? Help；Ctrl+Shift+O Transcript view menu。',
      '模式：Shift+Tab 循环 permission mode；Ctrl+M 打开 permission mode picker；Ctrl+Shift+E 打开/循环 reasoning effort，Ctrl+T 是保留的旧式循环快捷键。',
      '面板：Ctrl+Shift+V Preview；Ctrl+Shift+D Diff；Ctrl+` Terminal（若平台/菜单映射可用）。',
      '缩放：Ctrl+wheel、Ctrl+=、Ctrl+-、Ctrl+0。',
      'Mac 文本编辑使用 Cmd+C/V/X/Z/Shift+Z；Windows/Linux 使用 Ctrl 对应组合。',
    ),
    aliases: ['快捷键', 'shortcut', 'keybinding', '键盘', '热键', 'hotkey', 'Cmd+K', 'Ctrl+K'],
    nextTopics: ['command-system', 'composer', 'sidebar-resize'],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    summary:
      '优先看 Settings/Providers、MCP diagnostics、DevTools console 和 ~/.kodax/space/logs。',
    body: text(
      '常见问题：',
      '- No provider/key：到 Settings -> Providers 配 key，或确认环境变量。',
      '- AI 读不到文件：确认已打开项目目录，路径引用是否在 workspace 内。',
      '- Partner 不可点：v0.1.30+ 正常应启用；检查版本、当前 surface 和本地状态，并查看 DevTools/logs。',
      '- External Agent 不可选：确认使用 v0.1.44、Reference 注册已启用且实时 preflight 通过；Runtime 配置的 A2A 还要求 Coder daemon 能力协商成功，MCP Tasks/受治理 HTTP 当前不会出现。历史 Session 没有任务应显示空态；真实读取错误可点击“重试”。',
      '- Coder daemon 异常：先记录 Space/KodaX 版本、runId、连接状态和日志。v0.1.44 可在 Settings -> Runtime -> Coder runtime mode 选择 Embedded 后点击“切换并重启”；必须先结束 Space 任务，且 daemon 的其他客户端、active/queued work、Workflow、Agent Turn 和 pending interaction 都会安全阻止切换。KODAX_SPACE_RUNTIME_HOST 只作为旧配置的一次迁移种子，不应覆盖 version 3 的用户偏好。若启动遇到 inline owner，不要删除 `~/.kodax`；让 SDK 原子 reconciliation 判定 stale/active/unverifiable。',
      '- 集成配置异常：只检查报错点名的 ~/.kodax/integrations/*.json，不要删除整个 integrations 目录。无效更新会继续使用 last-known-good；修复文件后 Settings -> Runtime 通常会在数秒内自动恢复 healthy。这里也可预览并执行 SDK 的旧配置迁移；迁移不会覆盖已有目标，也不会默认删除旧字段。',
      '- 关闭按钮行为不符合预期：检查 Settings -> Preferences -> Close button behavior。最小化到托盘后应显示 KodaX Space 托盘图标；Windows、macOS 与 Linux 的真正退出都应安全停止 Runtime。若停止失败，Space 应自动恢复可见窗口；没有托盘/窗口却持续驻留 Space 自动拉起的 daemon 属于故障。',
      '- 完整退出长时间进行中：Windows 可从托盘重开查看同一条 settlement 已用时；普通成功退出不发系统通知，失败会恢复窗口。',
      '- Windows ACL recovery 阻断：当前源码会自动重试同一 boot 的临时 unconfirmed-owner；等待或重新打开 Space 即可继续观察。若精确 owner 仍活跃，先让对应工作正常结束；持续无法收敛时打开诊断目录并提交脱敏日志。不要删除 effect/exit lock、手工修改 ACL、触发 Setup 或 UAC。',
      '- 原生数字角标不清除：打开对应 Session 清除未读结果；permission/AskUser 必须实际解决或取消。同一 Session 只计一次，部分 Linux 桌面不支持数字角标。',
      '- Terminal 找不到命令：检查 Settings -> Preferences -> Terminal Shell，以及所选 shell 登录环境的 PATH；Space PTY 与 Coder 命令工具应使用同一脱敏执行环境。',
      '- 普通查询闪 cmd/console 窗口：KodaX 0.7.77 保留非交互子进程隐藏。若仍出现，它不是 Terminal 面板；请记录 Space/KodaX 版本、触发操作与进程名，按回归问题报告。',
      '- 排队气泡不消失：确认是否已出现相同 inputId 对应的真实用户 transcript 边界；若安全窗口关闭或 durable delivery 事件持久化失败应恢复草稿，后者仍保持 Runtime queued 且只发出不含正文的 warning；终态未送达应显示红色失败气泡，而不是永久排队。记录 sessionId、runId、inputId 和 session log。',
      '- 子 Agent 状态异常：普通 progress 不应唤醒模型侧 wait_agent，子正文/thinking/tools 不应进入 root transcript；检查 Agents/Workflow 活动面，并记录 actorPath、turnId 和 Runtime 日志。',
      '- 压缩恢复异常：检查 compaction entry、first-kept pointer 与压缩后附件是否仍在同一 active lineage；最新版会兼容旧的无后缀 checkpoint，但不会凭空恢复升级前已经丢失的字节。',
      '- 上下文数字看起来不一致：上下文百分比按自动压缩阈值而不是模型最大上下文计算；会话 Token 还累计子 Agent 和历史 Provider 调用。新 Session 要完成一次模型请求后才有精确构成。',
      '- 文件存在却提示无法定位：若提示路径不在 KodaX 已授权目录，请打开正确项目或使用受支持的项目/Delivery 边界；这与文件不存在是两种状态。',
      '- PowerShell Auto 权限异常：-Path 中含 [] 会按通配符升级确认；确需精确方括号文件名时使用 -LiteralPath/PSPath。若行为不同，请记录完整参数形态但不要附带密钥或文件正文。',
      '- Quick Ask 不工作：需要先打开项目；它使用临时 plan-mode session。',
      '- MCP 工具不可见：确认 server 位于 ~/.kodax/integrations/mcp.json 或 <project>/.kodax/integrations/mcp.json；打开 MCP 面板 Refresh/Reload config，查看 source、server error 和 diagnostics。旧 config.json#mcpServers 只用于迁移兼容。',
      '- 语言切换后仍有英文：模型输出、日志、专业面板和 provider 内容可能仍保留英文。',
      '- UI 状态异常：检查 ~/.kodax/space/logs 与 DevTools console；极端情况备份并重置 ~/.kodax/space/state.json。',
      '',
      '反馈 bug 时提供版本号、项目状态、复现步骤、相关日志和截图。',
    ),
    aliases: [
      '问题',
      '排错',
      'troubleshoot',
      'debug',
      '日志',
      'log',
      '报错',
      'error',
      '白屏',
      '卡死',
    ],
    nextTopics: [
      'config',
      'providers',
      'context-window-and-session-tokens',
      'agent-coordination',
      'mcp',
    ],
  },
];

/**
 * Build the effective Space manual only after the caller has dynamically loaded
 * the ESM-only KodaX /coding export. The Electron main bundle is CommonJS, so a
 * runtime static import here would become require() and fail before app startup.
 */
export function buildSpaceManual(sdk: SdkManualModule): {
  readonly productName: typeof SPACE_PRODUCT_NAME;
  readonly baseTopics: SdkManualModule['KODAX_UNDERLYING_CAPABILITY_TOPICS'];
  readonly topics: readonly KodaXManualTopicInput[];
} {
  const baseTopics = [...sdk.KODAX_UNDERLYING_CAPABILITY_TOPICS];
  const sdkBaseTopicIds = new Set<string>(baseTopics);
  return {
    productName: SPACE_PRODUCT_NAME,
    baseTopics,
    topics: SPACE_MANUAL_TOPIC_OVERLAYS.map((topic) =>
      inheritSdkManualTopic(topic, sdkBaseTopicIds, sdk.MANUAL_REGISTRY),
    ),
  };
}
