// Channel registry — single source of truth.
//
// 新加 channel 步骤：
//   1) 在 channels/<name>.ts 写定义（包含 name / direction / input / output 或 payload）
//   2) import 到本文件，加进 invokeChannels 或 pushChannels 字面量对象
//   3) main 侧写 handler 用 registerChannel(...)
//   4) renderer 侧通过类型推导自动得到正确签名
//
// 为什么用两个 map 而不是 union：
//   - invoke 与 push 的 shape 不同（前者 input+output，后者 payload）
//   - TypeScript 的 discriminated union 在 mapped types 里推导成本高、可读性差
//   - 显式两个 map 让类型 + 运行时 allowlist 同源派生，preload 拿来直接用

import { versionChannel } from './version.js';
import { connectorInvokeChannels, connectorPushChannels } from './partner-connector.js';
import {
  spaceExtensionsListChannel,
  spaceExtensionsInstallChannel,
  spaceExtensionsSetEnabledChannel,
  spaceExtensionsUninstallChannel,
  spaceExtensionsViewChannel,
  spaceExtensionsChangedChannel,
} from './space-extension.js';
import {
  spaceExtensionsCatalogChannel,
  spaceExtensionsResolveExpertChannel,
  spaceExtensionsExpertSaveChannel,
  spaceExtensionsExpertDeleteChannel,
  sessionPartnerExpertGetChannel,
  sessionPartnerExpertSetChannel,
  sessionPartnerExpertChangedChannel,
} from './partner-expert.js';
import { sandboxRefreshChannel, sandboxSetupChannel, sandboxStatusChannel } from './sandbox.js';
import {
  runtimeConnectionChangedChannel,
  runtimeProfileChangedChannel,
  runtimeProfileSnapshotChannel,
  sessionLiveChangedChannel,
  sessionLiveInvalidatedChannel,
  sessionLiveSnapshotChannel,
} from './runtime.js';
import { repointelStatusChannel, repointelPrewarmChannel } from './repointel.js';
import {
  handoffAcceptChannel,
  handoffChangedChannel,
  handoffDismissChannel,
  handoffListChannel,
} from './handoff.js';
import {
  sessionCreateChannel,
  sessionPromoteEphemeralChannel,
  sessionSendChannel,
  sessionCancelChannel,
  sessionListChannel,
  sessionDeleteChannel,
  sessionSetTitleChannel,
  sessionSetReasoningModeChannel,
  sessionSetProviderChannel,
  sessionSetPermissionModeChannel,
  sessionSetAutoModeEngineChannel,
  sessionSetAgentModeChannel,
  sessionForkChannel,
  sessionRewindChannel,
  sessionAgentsMdChannel,
  sessionAgentsMdSaveChannel,
  sessionHistoryChannel,
  sessionLocalNoticeAppendChannel,
  sessionLocalNoticeReplaceChannel,
  sessionListRunningChannel,
  sessionEventChannel,
} from './session.js';
import {
  projectListChannel,
  projectOpenDialogChannel,
  projectRecentAddChannel,
  projectRecentRemoveChannel,
  projectRecentRenameChannel,
  projectRecentSetArchivedChannel,
  projectGitStatsChannel,
  projectGitStatusChannel,
  projectFileSearchChannel,
  projectGitDiffChannel,
  projectGitChangesChannel,
  projectGitFileDiffChannel,
} from './project.js';
import {
  permissionRequestChannel,
  permissionCancelledChannel,
  permissionAnswerChannel,
  permissionListChannel,
  permissionRevokeChannel,
} from './permission.js';
import { askUserRequestChannel, askUserReplyChannel, askUserCancelledChannel } from './ask-user.js';
import { slashDiscoverChannel, slashExecChannel } from './slash.js';
import { skillDiscoverChannel, skillInstallChannel, skillInvokeChannel } from './skill.js';
import {
  agentDiscoverChannel,
  agentActorSnapshotChannel,
  agentActorChangedChannel,
  externalAgentStatusChannel,
  externalAgentRegistrationListChannel,
  externalAgentReferenceUpsertChannel,
  externalAgentRegistrationRemoveChannel,
  externalAgentDispatchableListChannel,
  externalAgentPreflightChannel,
  externalAgentTaskListChannel,
  externalAgentTaskStartChannel,
  externalAgentTaskEventsChannel,
  externalAgentTaskSendInputChannel,
  externalAgentTaskCancelChannel,
  externalAgentTaskReconcileChannel,
} from './agent.js';
import {
  mcpDiscoverChannel,
  mcpServersChannel,
  mcpStartChannel,
  mcpStopChannel,
  mcpLogsChannel,
  mcpToolsChannel,
  mcpReloadChannel,
} from './mcp.js';
import { kodaxGetDefaultsChannel } from './kodax.js';
import {
  adminPolicyGetChannel,
  adminPolicySetChannel,
  adminPolicyExportChannel,
  adminAuditListChannel,
  adminAuditExportChannel,
} from './admin.js';
import { kodaxQueueGetChannel, kodaxQueueChangedChannel } from './queue.js';
import {
  providerListChannel,
  providerSetKeyChannel,
  providerRemoveKeyChannel,
  providerTestChannel,
  providerSetDefaultChannel,
  providerAddCustomChannel,
  providerUpdateCustomChannel,
  providerRemoveCustomChannel,
  providerModelContextWindowChannel,
} from './provider.js';
import {
  filesTreeChannel,
  filesReadChannel,
  filesReadBinaryChannel,
  filesStatChannel,
  filesWebPreviewChannel,
  filesDiffChannel,
} from './files.js';
import {
  partnerSourcesListChannel,
  partnerSourcesAddChannel,
  partnerSourcesRemoveChannel,
} from './partner-source.js';
import {
  partnerCitationResolveChannel,
  partnerKnowledgeCatalogChannel,
  partnerKnowledgeRefreshChannel,
  partnerKnowledgeScopeSetChannel,
  partnerKnowledgeSelectChannel,
  partnerKnowledgeTraceReadChannel,
  partnerMaterialsAdoptChannel,
  partnerMaterialsCatalogChannel,
  partnerMaterialsRemoveChannel,
  partnerMaterialsSelectChannel,
} from './partner-knowledge.js';
import {
  partnerKbSummaryChannel,
  partnerKbPagesChannel,
  partnerKbReadPageChannel,
  partnerKbWritePageChannel,
  partnerKbSearchChannel,
  partnerKbRebuildIndexChannel,
  partnerKbLintChannel,
  partnerKbConfigGetChannel,
  partnerKbConfigSetChannel,
  partnerKbMaintenanceRunChannel,
  partnerKbMaintenanceLastChannel,
} from './partner-kb.js';
import {
  partnerFileProposalsListChannel,
  partnerFileProposalsGetChannel,
  partnerFileProposalsApplyChannel,
  partnerFileProposalsRejectChannel,
  partnerFileProposalsExportChannel,
  partnerFileProposalsChangedChannel,
} from './partner-file-proposal.js';
import {
  partnerDeliveriesListChannel,
  partnerDeliveriesGetChannel,
  partnerDeliveriesResolveChannel,
  partnerDeliveriesOutputRootChannel,
  partnerDeliveriesReadBinaryChannel,
  partnerDeliveriesChangedChannel,
} from './partner-delivery.js';
import {
  partnerCheckpointsListChannel,
  partnerCheckpointsGetChannel,
  partnerCheckpointsRollbackChannel,
  partnerCheckpointsChangedChannel,
} from './partner-checkpoint.js';
import { titlebarSetOverlayChannel } from './titlebar.js';
import {
  settingsGetChannel,
  settingsKodaxConfigApplyIntegrationMigrationChannel,
  settingsKodaxConfigGetChannel,
  settingsKodaxConfigPlanIntegrationMigrationChannel,
  settingsKodaxConfigSetCompactionChannel,
  settingsKodaxConfigSetSandboxChannel,
  settingsSetCoderRuntimeModeChannel,
  settingsSetDefaultWorkspaceChannel,
  settingsSetLanguageModeChannel,
  settingsSetTerminalShellChannel,
  settingsSetWindowCloseBehaviorChannel,
  settingsSetRuntimeDefaultsChannel,
} from './settings.js';
import {
  licenseExportRequestChannel,
  licenseGetStatusChannel,
  licenseHasFeatureChannel,
  licenseImportEntitlementChannel,
  licenseRequireEntitlementChannel,
} from './license.js';
import { notificationShowChannel, notificationClickedChannel } from './notification.js';
import {
  partnerBrowserNavigatedChannel,
  windowActivityChannel,
  windowCompleteExitProgressChannel,
  windowControlChannel,
  windowSetBadgeCountChannel,
  windowStateChannel,
} from './window.js';
import { updaterCheckChannel, updaterInstallChannel, updaterStatusChannel } from './updater.js';
import {
  mcpbInstallChannel,
  mcpbUninstallChannel,
  mcpbListChannel,
  mcpbChangedChannel,
} from './mcpb.js';
import {
  terminalCreateChannel,
  terminalWriteChannel,
  terminalResizeChannel,
  terminalKillChannel,
  terminalOutputChannel,
  terminalExitChannel,
} from './terminal.js';
import {
  clipboardSaveImageChannel,
  clipboardReadImageChannel,
  clipboardCleanupSessionChannel,
  clipboardDiscardImageChannel,
} from './clipboard.js';
import {
  shellRevealPathChannel,
  shellOpenDirectoryChannel,
  shellOpenExternalChannel,
} from './shell.js';
import {
  artifactCreateChannel,
  artifactListChannel,
  artifactReadChannel,
  artifactReadBinaryChannel,
  artifactDeleteChannel,
  artifactExportChannel,
  artifactOpenWindowChannel,
  artifactPreviewFileChannel,
  artifactChangedChannel,
} from './artifact.js';
import {
  workflowListChannel,
  workflowGetChannel,
  workflowEventChannel,
  workflowActivityChannel,
  workflowStopChannel,
  workflowPauseChannel,
  workflowResumeChannel,
  workflowRenameChannel,
  workflowDeleteChannel,
  workflowRerunChannel,
  workflowPruneChannel,
  workflowLibraryChannel,
  workflowPreflightChannel,
  workflowStartChannel,
  workflowSaveChannel,
  workflowSavedRenameChannel,
  workflowSavedDeleteChannel,
  workflowPolicyGetChannel,
  workflowPolicySetChannel,
  workflowResultChannel,
} from './workflow.js';
import {
  memoryListChannel,
  memoryProposalChannel,
  memoryApproveChannel,
  memoryRejectChannel,
  memoryReadRefChannel,
  memoryCurateChannel,
  memoryPackChannel,
} from './memory.js';
import {
  learningAcknowledgeChannel,
  learningActionChannel,
  learningChangedChannel,
  learningGetChannel,
  learningListChannel,
} from './learning.js';
import { diagnosticsExportChannel, diagnosticsReportChannel } from './diagnostics.js';
import { spaceControlRequestedChannel, spaceControlResolveChannel } from './space-control.js';

export const invokeChannels = {
  ...connectorInvokeChannels,
  [spaceExtensionsListChannel.name]: spaceExtensionsListChannel,
  [spaceExtensionsInstallChannel.name]: spaceExtensionsInstallChannel,
  [spaceExtensionsSetEnabledChannel.name]: spaceExtensionsSetEnabledChannel,
  [spaceExtensionsUninstallChannel.name]: spaceExtensionsUninstallChannel,
  [spaceExtensionsViewChannel.name]: spaceExtensionsViewChannel,
  [spaceExtensionsCatalogChannel.name]: spaceExtensionsCatalogChannel,
  [spaceExtensionsResolveExpertChannel.name]: spaceExtensionsResolveExpertChannel,
  [spaceExtensionsExpertSaveChannel.name]: spaceExtensionsExpertSaveChannel,
  [spaceExtensionsExpertDeleteChannel.name]: spaceExtensionsExpertDeleteChannel,
  [sessionPartnerExpertGetChannel.name]: sessionPartnerExpertGetChannel,
  [sessionPartnerExpertSetChannel.name]: sessionPartnerExpertSetChannel,
  [versionChannel.name]: versionChannel,
  [sandboxStatusChannel.name]: sandboxStatusChannel,
  [sandboxRefreshChannel.name]: sandboxRefreshChannel,
  [sandboxSetupChannel.name]: sandboxSetupChannel,
  [runtimeProfileSnapshotChannel.name]: runtimeProfileSnapshotChannel,
  [sessionLiveSnapshotChannel.name]: sessionLiveSnapshotChannel,
  [diagnosticsReportChannel.name]: diagnosticsReportChannel,
  [diagnosticsExportChannel.name]: diagnosticsExportChannel,
  [spaceControlResolveChannel.name]: spaceControlResolveChannel,
  [repointelStatusChannel.name]: repointelStatusChannel,
  [repointelPrewarmChannel.name]: repointelPrewarmChannel,
  [handoffListChannel.name]: handoffListChannel,
  [handoffAcceptChannel.name]: handoffAcceptChannel,
  [handoffDismissChannel.name]: handoffDismissChannel,
  [sessionCreateChannel.name]: sessionCreateChannel,
  [sessionPromoteEphemeralChannel.name]: sessionPromoteEphemeralChannel,
  [sessionSendChannel.name]: sessionSendChannel,
  [sessionCancelChannel.name]: sessionCancelChannel,
  [sessionListChannel.name]: sessionListChannel,
  [sessionDeleteChannel.name]: sessionDeleteChannel,
  [sessionSetTitleChannel.name]: sessionSetTitleChannel,
  [sessionSetReasoningModeChannel.name]: sessionSetReasoningModeChannel,
  [sessionSetProviderChannel.name]: sessionSetProviderChannel,
  [sessionSetPermissionModeChannel.name]: sessionSetPermissionModeChannel,
  [sessionSetAutoModeEngineChannel.name]: sessionSetAutoModeEngineChannel,
  [sessionSetAgentModeChannel.name]: sessionSetAgentModeChannel,
  [sessionForkChannel.name]: sessionForkChannel,
  [sessionRewindChannel.name]: sessionRewindChannel,
  [sessionAgentsMdChannel.name]: sessionAgentsMdChannel,
  [sessionAgentsMdSaveChannel.name]: sessionAgentsMdSaveChannel,
  [sessionHistoryChannel.name]: sessionHistoryChannel,
  [sessionLocalNoticeAppendChannel.name]: sessionLocalNoticeAppendChannel,
  [sessionLocalNoticeReplaceChannel.name]: sessionLocalNoticeReplaceChannel,
  [sessionListRunningChannel.name]: sessionListRunningChannel,
  [projectListChannel.name]: projectListChannel,
  [projectOpenDialogChannel.name]: projectOpenDialogChannel,
  [projectRecentAddChannel.name]: projectRecentAddChannel,
  [projectRecentRemoveChannel.name]: projectRecentRemoveChannel,
  [projectRecentRenameChannel.name]: projectRecentRenameChannel,
  [projectRecentSetArchivedChannel.name]: projectRecentSetArchivedChannel,
  [projectGitStatsChannel.name]: projectGitStatsChannel,
  [projectGitStatusChannel.name]: projectGitStatusChannel,
  [projectFileSearchChannel.name]: projectFileSearchChannel,
  [projectGitDiffChannel.name]: projectGitDiffChannel,
  [projectGitChangesChannel.name]: projectGitChangesChannel,
  [projectGitFileDiffChannel.name]: projectGitFileDiffChannel,
  [permissionAnswerChannel.name]: permissionAnswerChannel,
  [permissionListChannel.name]: permissionListChannel,
  [permissionRevokeChannel.name]: permissionRevokeChannel,
  [askUserReplyChannel.name]: askUserReplyChannel,
  [slashDiscoverChannel.name]: slashDiscoverChannel,
  [slashExecChannel.name]: slashExecChannel,
  [skillDiscoverChannel.name]: skillDiscoverChannel,
  [skillInvokeChannel.name]: skillInvokeChannel,
  [skillInstallChannel.name]: skillInstallChannel,
  [agentDiscoverChannel.name]: agentDiscoverChannel,
  [agentActorSnapshotChannel.name]: agentActorSnapshotChannel,
  [externalAgentStatusChannel.name]: externalAgentStatusChannel,
  [externalAgentRegistrationListChannel.name]: externalAgentRegistrationListChannel,
  [externalAgentReferenceUpsertChannel.name]: externalAgentReferenceUpsertChannel,
  [externalAgentRegistrationRemoveChannel.name]: externalAgentRegistrationRemoveChannel,
  [externalAgentDispatchableListChannel.name]: externalAgentDispatchableListChannel,
  [externalAgentPreflightChannel.name]: externalAgentPreflightChannel,
  [externalAgentTaskListChannel.name]: externalAgentTaskListChannel,
  [externalAgentTaskStartChannel.name]: externalAgentTaskStartChannel,
  [externalAgentTaskEventsChannel.name]: externalAgentTaskEventsChannel,
  [externalAgentTaskSendInputChannel.name]: externalAgentTaskSendInputChannel,
  [externalAgentTaskCancelChannel.name]: externalAgentTaskCancelChannel,
  [externalAgentTaskReconcileChannel.name]: externalAgentTaskReconcileChannel,
  [mcpDiscoverChannel.name]: mcpDiscoverChannel,
  [mcpServersChannel.name]: mcpServersChannel,
  [mcpStartChannel.name]: mcpStartChannel,
  [mcpStopChannel.name]: mcpStopChannel,
  [mcpLogsChannel.name]: mcpLogsChannel,
  [mcpToolsChannel.name]: mcpToolsChannel,
  [mcpReloadChannel.name]: mcpReloadChannel,
  [kodaxGetDefaultsChannel.name]: kodaxGetDefaultsChannel,
  [adminPolicyGetChannel.name]: adminPolicyGetChannel,
  [adminPolicySetChannel.name]: adminPolicySetChannel,
  [adminPolicyExportChannel.name]: adminPolicyExportChannel,
  [adminAuditListChannel.name]: adminAuditListChannel,
  [adminAuditExportChannel.name]: adminAuditExportChannel,
  [kodaxQueueGetChannel.name]: kodaxQueueGetChannel,
  [providerListChannel.name]: providerListChannel,
  [providerSetKeyChannel.name]: providerSetKeyChannel,
  [providerRemoveKeyChannel.name]: providerRemoveKeyChannel,
  [providerTestChannel.name]: providerTestChannel,
  [providerSetDefaultChannel.name]: providerSetDefaultChannel,
  [providerAddCustomChannel.name]: providerAddCustomChannel,
  [providerUpdateCustomChannel.name]: providerUpdateCustomChannel,
  [providerRemoveCustomChannel.name]: providerRemoveCustomChannel,
  [providerModelContextWindowChannel.name]: providerModelContextWindowChannel,
  [filesTreeChannel.name]: filesTreeChannel,
  [filesReadChannel.name]: filesReadChannel,
  [filesReadBinaryChannel.name]: filesReadBinaryChannel,
  [filesStatChannel.name]: filesStatChannel,
  [filesWebPreviewChannel.name]: filesWebPreviewChannel,
  [filesDiffChannel.name]: filesDiffChannel,
  [partnerSourcesListChannel.name]: partnerSourcesListChannel,
  [partnerSourcesAddChannel.name]: partnerSourcesAddChannel,
  [partnerSourcesRemoveChannel.name]: partnerSourcesRemoveChannel,
  [partnerKnowledgeCatalogChannel.name]: partnerKnowledgeCatalogChannel,
  [partnerKnowledgeSelectChannel.name]: partnerKnowledgeSelectChannel,
  [partnerKnowledgeRefreshChannel.name]: partnerKnowledgeRefreshChannel,
  [partnerKnowledgeScopeSetChannel.name]: partnerKnowledgeScopeSetChannel,
  [partnerKnowledgeTraceReadChannel.name]: partnerKnowledgeTraceReadChannel,
  [partnerCitationResolveChannel.name]: partnerCitationResolveChannel,
  [partnerMaterialsCatalogChannel.name]: partnerMaterialsCatalogChannel,
  [partnerMaterialsSelectChannel.name]: partnerMaterialsSelectChannel,
  [partnerMaterialsAdoptChannel.name]: partnerMaterialsAdoptChannel,
  [partnerMaterialsRemoveChannel.name]: partnerMaterialsRemoveChannel,
  [partnerKbSummaryChannel.name]: partnerKbSummaryChannel,
  [partnerKbPagesChannel.name]: partnerKbPagesChannel,
  [partnerKbReadPageChannel.name]: partnerKbReadPageChannel,
  [partnerKbWritePageChannel.name]: partnerKbWritePageChannel,
  [partnerKbSearchChannel.name]: partnerKbSearchChannel,
  [partnerKbRebuildIndexChannel.name]: partnerKbRebuildIndexChannel,
  [partnerKbLintChannel.name]: partnerKbLintChannel,
  [partnerKbConfigGetChannel.name]: partnerKbConfigGetChannel,
  [partnerKbConfigSetChannel.name]: partnerKbConfigSetChannel,
  [partnerKbMaintenanceRunChannel.name]: partnerKbMaintenanceRunChannel,
  [partnerKbMaintenanceLastChannel.name]: partnerKbMaintenanceLastChannel,
  [partnerFileProposalsListChannel.name]: partnerFileProposalsListChannel,
  [partnerFileProposalsGetChannel.name]: partnerFileProposalsGetChannel,
  [partnerFileProposalsApplyChannel.name]: partnerFileProposalsApplyChannel,
  [partnerFileProposalsRejectChannel.name]: partnerFileProposalsRejectChannel,
  [partnerFileProposalsExportChannel.name]: partnerFileProposalsExportChannel,
  [partnerDeliveriesListChannel.name]: partnerDeliveriesListChannel,
  [partnerDeliveriesGetChannel.name]: partnerDeliveriesGetChannel,
  [partnerDeliveriesResolveChannel.name]: partnerDeliveriesResolveChannel,
  [partnerDeliveriesOutputRootChannel.name]: partnerDeliveriesOutputRootChannel,
  [partnerDeliveriesReadBinaryChannel.name]: partnerDeliveriesReadBinaryChannel,
  [partnerCheckpointsListChannel.name]: partnerCheckpointsListChannel,
  [partnerCheckpointsGetChannel.name]: partnerCheckpointsGetChannel,
  [partnerCheckpointsRollbackChannel.name]: partnerCheckpointsRollbackChannel,
  [titlebarSetOverlayChannel.name]: titlebarSetOverlayChannel,
  [settingsGetChannel.name]: settingsGetChannel,
  [settingsSetCoderRuntimeModeChannel.name]: settingsSetCoderRuntimeModeChannel,
  [settingsSetDefaultWorkspaceChannel.name]: settingsSetDefaultWorkspaceChannel,
  [settingsSetLanguageModeChannel.name]: settingsSetLanguageModeChannel,
  [settingsSetTerminalShellChannel.name]: settingsSetTerminalShellChannel,
  [settingsSetWindowCloseBehaviorChannel.name]: settingsSetWindowCloseBehaviorChannel,
  [settingsSetRuntimeDefaultsChannel.name]: settingsSetRuntimeDefaultsChannel,
  [settingsKodaxConfigGetChannel.name]: settingsKodaxConfigGetChannel,
  [settingsKodaxConfigSetCompactionChannel.name]: settingsKodaxConfigSetCompactionChannel,
  [settingsKodaxConfigSetSandboxChannel.name]: settingsKodaxConfigSetSandboxChannel,
  [settingsKodaxConfigPlanIntegrationMigrationChannel.name]:
    settingsKodaxConfigPlanIntegrationMigrationChannel,
  [settingsKodaxConfigApplyIntegrationMigrationChannel.name]:
    settingsKodaxConfigApplyIntegrationMigrationChannel,
  [licenseGetStatusChannel.name]: licenseGetStatusChannel,
  [licenseImportEntitlementChannel.name]: licenseImportEntitlementChannel,
  [licenseExportRequestChannel.name]: licenseExportRequestChannel,
  [licenseRequireEntitlementChannel.name]: licenseRequireEntitlementChannel,
  [licenseHasFeatureChannel.name]: licenseHasFeatureChannel,
  [notificationShowChannel.name]: notificationShowChannel,
  [windowStateChannel.name]: windowStateChannel,
  [windowControlChannel.name]: windowControlChannel,
  [windowSetBadgeCountChannel.name]: windowSetBadgeCountChannel,
  [updaterCheckChannel.name]: updaterCheckChannel,
  [updaterInstallChannel.name]: updaterInstallChannel,
  [mcpbInstallChannel.name]: mcpbInstallChannel,
  [mcpbUninstallChannel.name]: mcpbUninstallChannel,
  [mcpbListChannel.name]: mcpbListChannel,
  [terminalCreateChannel.name]: terminalCreateChannel,
  [terminalWriteChannel.name]: terminalWriteChannel,
  [terminalResizeChannel.name]: terminalResizeChannel,
  [terminalKillChannel.name]: terminalKillChannel,
  [clipboardSaveImageChannel.name]: clipboardSaveImageChannel,
  [clipboardReadImageChannel.name]: clipboardReadImageChannel,
  [clipboardCleanupSessionChannel.name]: clipboardCleanupSessionChannel,
  [clipboardDiscardImageChannel.name]: clipboardDiscardImageChannel,
  [shellRevealPathChannel.name]: shellRevealPathChannel,
  [shellOpenDirectoryChannel.name]: shellOpenDirectoryChannel,
  [shellOpenExternalChannel.name]: shellOpenExternalChannel,
  [artifactCreateChannel.name]: artifactCreateChannel,
  [artifactListChannel.name]: artifactListChannel,
  [artifactReadChannel.name]: artifactReadChannel,
  [artifactReadBinaryChannel.name]: artifactReadBinaryChannel,
  [artifactDeleteChannel.name]: artifactDeleteChannel,
  [artifactExportChannel.name]: artifactExportChannel,
  [artifactOpenWindowChannel.name]: artifactOpenWindowChannel,
  [artifactPreviewFileChannel.name]: artifactPreviewFileChannel,
  [workflowListChannel.name]: workflowListChannel,
  [workflowGetChannel.name]: workflowGetChannel,
  [workflowStopChannel.name]: workflowStopChannel,
  [workflowPauseChannel.name]: workflowPauseChannel,
  [workflowResumeChannel.name]: workflowResumeChannel,
  [workflowRenameChannel.name]: workflowRenameChannel,
  [workflowDeleteChannel.name]: workflowDeleteChannel,
  [workflowRerunChannel.name]: workflowRerunChannel,
  [workflowPruneChannel.name]: workflowPruneChannel,
  [workflowLibraryChannel.name]: workflowLibraryChannel,
  [workflowPreflightChannel.name]: workflowPreflightChannel,
  [workflowStartChannel.name]: workflowStartChannel,
  [workflowSaveChannel.name]: workflowSaveChannel,
  [workflowSavedRenameChannel.name]: workflowSavedRenameChannel,
  [workflowSavedDeleteChannel.name]: workflowSavedDeleteChannel,
  [workflowPolicyGetChannel.name]: workflowPolicyGetChannel,
  [workflowPolicySetChannel.name]: workflowPolicySetChannel,
  [workflowResultChannel.name]: workflowResultChannel,
  [memoryListChannel.name]: memoryListChannel,
  [memoryProposalChannel.name]: memoryProposalChannel,
  [memoryApproveChannel.name]: memoryApproveChannel,
  [memoryRejectChannel.name]: memoryRejectChannel,
  [memoryReadRefChannel.name]: memoryReadRefChannel,
  [memoryCurateChannel.name]: memoryCurateChannel,
  [memoryPackChannel.name]: memoryPackChannel,
  [learningListChannel.name]: learningListChannel,
  [learningGetChannel.name]: learningGetChannel,
  [learningActionChannel.name]: learningActionChannel,
  [learningAcknowledgeChannel.name]: learningAcknowledgeChannel,
} as const;

export const pushChannels = {
  ...connectorPushChannels,
  [spaceExtensionsChangedChannel.name]: spaceExtensionsChangedChannel,
  [sessionPartnerExpertChangedChannel.name]: sessionPartnerExpertChangedChannel,
  [runtimeConnectionChangedChannel.name]: runtimeConnectionChangedChannel,
  [runtimeProfileChangedChannel.name]: runtimeProfileChangedChannel,
  [sessionLiveChangedChannel.name]: sessionLiveChangedChannel,
  [sessionLiveInvalidatedChannel.name]: sessionLiveInvalidatedChannel,
  [agentActorChangedChannel.name]: agentActorChangedChannel,
  [spaceControlRequestedChannel.name]: spaceControlRequestedChannel,
  [sessionEventChannel.name]: sessionEventChannel,
  [artifactChangedChannel.name]: artifactChangedChannel,
  [partnerFileProposalsChangedChannel.name]: partnerFileProposalsChangedChannel,
  [partnerDeliveriesChangedChannel.name]: partnerDeliveriesChangedChannel,
  [partnerCheckpointsChangedChannel.name]: partnerCheckpointsChangedChannel,
  [permissionRequestChannel.name]: permissionRequestChannel,
  [permissionCancelledChannel.name]: permissionCancelledChannel,
  [askUserRequestChannel.name]: askUserRequestChannel,
  [askUserCancelledChannel.name]: askUserCancelledChannel,
  [kodaxQueueChangedChannel.name]: kodaxQueueChangedChannel,
  [notificationClickedChannel.name]: notificationClickedChannel,
  [partnerBrowserNavigatedChannel.name]: partnerBrowserNavigatedChannel,
  [windowActivityChannel.name]: windowActivityChannel,
  [windowCompleteExitProgressChannel.name]: windowCompleteExitProgressChannel,
  [updaterStatusChannel.name]: updaterStatusChannel,
  [mcpbChangedChannel.name]: mcpbChangedChannel,
  [terminalOutputChannel.name]: terminalOutputChannel,
  [terminalExitChannel.name]: terminalExitChannel,
  [workflowEventChannel.name]: workflowEventChannel,
  [workflowActivityChannel.name]: workflowActivityChannel,
  [handoffChangedChannel.name]: handoffChangedChannel,
  [learningChangedChannel.name]: learningChangedChannel,
} as const;

export type InvokeChannels = typeof invokeChannels;
export type PushChannels = typeof pushChannels;
